MegafonWebLab/megafon-ui

- packages/ui-core/src/components/Select/Select.docz.tsx
- packages/ui-core/src/components/Select/Select.mdx
- packages/ui-core/src/components/Select/Select.tsx
> fix(select): edit item value prop type

- packages/ui-core/src/components/Notification/Notification.mdx
- packages/ui-core/src/components/Notification/Notification.test.tsx
- packages/ui-core/src/components/Notification/Notification.tsx
- packages/ui-core/src/components/Select/Select.mdx
- packages/ui-core/src/components/Select/Select.tsx
- packages/ui-core/src/components/Tile/Tile.mdx
- packages/ui-core/src/components/Tile/Tile.tsx
Changed enum to object literal
> Fix types in Select, Tile

- packages/ui-core/src/components/TextField/TextField.mdx
- packages/ui-core/src/components/TextField/TextField.test.tsx
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
added inputmode for input. Required to select the keyboard type on mobile devices.
> feat(textfield): added inputmode for input

- packages/ui-core/src/components/Button/Button.less
- packages/ui-core/src/components/Button/Button.test.tsx
- packages/ui-core/src/components/Button/Button.tsx
- packages/ui-core/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/ui-core/src/components/Button/doc/Button.example.mdx
- packages/ui-core/src/components/Preloader/Preloader.less
- packages/ui-core/src/components/Preloader/Preloader.test.tsx
- packages/ui-core/src/components/Preloader/Preloader.tsx
- packages/ui-core/src/components/Preloader/__snapshots__/Preloader.test.tsx.snap
- packages/ui-core/src/components/Preloader/doc/Preloader.example.mdx
added preloader in button instead of spinner
> fix(button, preloader): loader into button

- packages/ui-shared/src/components/AccordionBox/AccordionBox.test.tsx
- packages/ui-shared/src/components/AccordionBox/AccordionBox.tsx
- packages/ui-shared/src/components/AccordionBox/__snapshots__/AccordionBox.test.tsx.snap
- packages/ui-shared/src/components/AccordionBox/doc/AccordionBox.example.mdx
- packages/ui-shared/src/components/AccordionBox/doc/AccordionBox.mdx
> feat(accordionbox): add component AccordionBox to constructor

- packages/ui-core/src/components/Search/Search.less
when user double-clicks on control element
> fix(search): prevent placeholder selection

- packages/ui-core/src/components/Calendar/Calendar.test.tsx
- packages/ui-core/src/components/Calendar/Calendar.tsx
- packages/ui-core/src/components/Calendar/components/Month/Month.less
- packages/ui-core/src/components/Calendar/doc/Calendar.docz.tsx
- packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
Fixes z-index bugs, renamed callback function property for better consistency
> Calendar fixes

- doczrc.js
Reverts MegafonWebLab/megafon-ui#426
> Revert "docs(docz): update base url"

- .github/workflows/deploy-docs.yaml
- README.md
Reverts MegafonWebLab/megafon-ui#423
> Revert "docs: add custom domain"

- packages/ui-shared/src/components/BannerBox/BannerBox.test.tsx
- packages/ui-shared/src/components/BannerBox/BannerBox.tsx
- packages/ui-shared/src/components/BannerBox/__snapshots__/BannerBox.test.tsx.snap
- packages/ui-shared/src/components/BannerBox/doc/BannerBox.docz.tsx
- packages/ui-shared/src/components/BannerBox/doc/BannerBox.example.mdx
- packages/ui-shared/src/components/BannerBox/doc/BannerBox.mdx
created component for the constructor
> feat(component): add BannerBox component

- packages/ui-core/src/icons/System/16/Copy_16.svg
- packages/ui-core/src/icons/System/24/Copy_24.svg
- packages/ui-core/src/icons/System/32/Copy_32.svg
> feat(icons): added new Copy icon

- packages/ui-core/src/components/Carousel/Carousel.less
- packages/ui-core/src/components/Carousel/Carousel.tsx
- packages/ui-core/src/components/Carousel/__snapshots__/Carousel.test.tsx.snap
- packages/ui-core/src/components/Carousel/doc/Carousel.example.mdx
Added hiding dots and buttons arrow when few slides
> fix(carousel): update carousel component

- packages/ui-core/src/components/List/ListItem.less
Убраны лишние отступы которые дублировались и в родителе. Оставлены только отступы между элементами списка.
> fix(ListItem): remove extra margins

- packages/ui-core/src/components/ContentArea/ContentArea.less
- packages/ui-core/src/components/ContentArea/ContentArea.test.tsx
- packages/ui-core/src/components/ContentArea/ContentArea.tsx
- packages/ui-core/src/components/ContentArea/__snapshots__/ContentArea.test.tsx.snap
BREAKING CHANGE: className prop was deleted. Added new prop for custom class names.
> feat(content area): added classes prop, added new disable indents range

- packages/ui-core/src/icons/System/16/Attach-file_16.svg
- packages/ui-core/src/icons/System/32/Attach-file_32.svg
BREAKING CHANGE: returned old icon attach-file
> fix(icons): returned old icon attach-file

- packages/ui-shared/src/components/Card/Card.less
- packages/ui-shared/src/components/Card/Card.test.tsx
- packages/ui-shared/src/components/Card/Card.tsx
- packages/ui-shared/src/components/Card/__snapshots__/Card.test.tsx.snap
- packages/ui-shared/src/components/Card/doc/Card.example.mdx
- packages/ui-shared/src/components/CardsBox/__snapshots__/CardsBox.test.tsx.snap
add ability to set height of card to 100% with positioning of button and link at bottom of card when
height of container is greater than content
> feat(card): add fullHeight prop

- packages/ui-core/src/components/TextField/TextField.test.tsx
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
added typing support for number values
> fix(textfield): number value in typings

- packages/ui-shared/src/components/Property/Property.less
- packages/ui-shared/src/components/Property/Property.tsx
- packages/ui-shared/src/components/Property/__snapshots__/Property.test.tsx.snap
- packages/ui-shared/src/components/Property/doc/Property.example.mdx
- packages/ui-shared/src/components/Property/doc/Property.mdx
- packages/ui-shared/src/components/Property/doc/Property.props.mdx
Delete absolute value position and fix content width
> style(property): css refactoring

- packages/ui-core/src/components/RadioButton/RadioButton.test.tsx
- packages/ui-core/src/components/RadioButton/RadioButton.tsx
add reference to input element in RadioButton component
> fix(radiobutton): add props inputRef

- packages/ui-core/src/components/Grid/Grid.tsx
- packages/ui-core/src/components/Grid/GridColumn.tsx
- packages/ui-core/src/components/Grid/__snapshots__/Grid.test.tsx.snap
- packages/ui-shared/src/components/AccordionBox/__snapshots__/AccordionBox.test.tsx.snap
- packages/ui-shared/src/components/BenefitsIcons/__snapshots__/BenefitsIcons.test.tsx.snap
- packages/ui-shared/src/components/BenefitsPictures/__snapshots__/BenefitPictures.test.tsx.snap
- packages/ui-shared/src/components/ButtonBanner/__snapshots__/ButtonBanner.test.tsx.snap
- packages/ui-shared/src/components/CardsBox/__snapshots__/CardsBox.test.tsx.snap
- packages/ui-shared/src/components/DownloadLinks/__snapshots__/DownloadLinks.test.tsx.snap
- packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
- packages/ui-shared/src/components/Partners/__snapshots__/Partners.test.tsx.snap
- packages/ui-shared/src/components/StoreBanner/__snapshots__/StoreBanner.test.tsx.snap
- packages/ui-shared/src/components/TitleDescriptionBox/__snapshots__/TitleDescriptionBox.test.tsx.snap
- packages/ui-shared/src/components/VideoBlock/__snapshots__/VideoBlock.test.tsx.snap
Fixes when Element type added to function used as jsx expression with GridColumn inside. Rewritten to functional component
> Grid children type

- packages/ui-core/src/components/Tabs/Tabs.test.tsx
- packages/ui-core/src/components/Tabs/Tabs.tsx
- packages/ui-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
Reverts MegafonWebLab/megafon-ui#501
> Revert "refactor(tabs): replaced the old sticky tabs algorithm with intersect…"

- packages/ui-core/src/components/Select/Select.test.tsx
- packages/ui-core/src/components/Select/Select.tsx
- yarn.lock
add functions onOpened and onClosed in Select component
> fix(select): add props onOpened and onClosed

- packages/ui-shared/src/components/Steps/StepsItem.tsx
adds ReactNode type to text for convert function
BREAKING CHANGE: adds ReactNode type to text props for convert function
> feat(steps): edit steps item text type

- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Search/Search.tsx
> fix(search): update icon

- packages/ui-shared/src/components/Partners/Partners.test.tsx
- packages/ui-shared/src/components/Partners/Partners.tsx
- packages/ui-shared/src/components/Partners/__snapshots__/Partners.test.tsx.snap
BREAKING CHANGE: add props rootRef
> feat(partners): add props rootRef

- packages/ui-shared/src/components/BenefitsIcons/doc/BenefitsIcons.example.mdx
- packages/ui-shared/src/components/BenefitsIcons/style/BenefitsIconsTile.less
component must be in one line with title
> fix(benefits icons): delete padding from benefits

- packages/ui-core/src/components/Notification/Notification.less
> fix(notification): fix style

- packages/ui-core/src/components/Carousel/Carousel.tsx
- packages/ui-core/src/components/Carousel/__snapshots__/Carousel.test.tsx.snap
Добавил новое свойство  слайдера : пороговое значение для свайпа
> feat(carousel): add new prop threshold

- packages/ui-shared/src/components/CardsBox/CardsBox.test.tsx
- packages/ui-shared/src/components/CardsBox/CardsBox.tsx
> feat(cardsbox): add ref prop

- README.md
- packages/ui-helpers/README.md
Fixes README.md in main and @megafon/ui-helpers
> Readme fixes

- packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx
- packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
- packages/ui-shared/src/components/VideoBanner/__snapshots__/VideoBanner.test.tsx.snap
- packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.docz.tsx
- packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.example.mdx
- packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.props.mdx
BREAKING CHANGE: add buttonVisible prop in content
> feat(videobanner): props buttonTitle made optional

- packages/ui-core/src/components/Pagination/components/PaginationButton/PaginationButton.less
- packages/ui-core/src/components/Pagination/components/PaginationNavigation/PaginationNavigation.less
> fix(pagination): fix svg icons in safari

- packages/ui-core/src/components/Select/Select.test.tsx
- packages/ui-core/src/components/Select/Select.tsx
- packages/ui-core/src/components/Select/__snapshots__/Select.test.tsx.snap
- packages/ui-core/src/components/Select/doc/Select.docz.tsx
- packages/ui-core/src/components/Select/doc/Select.example.mdx
Add tracking on input change after chosen item
> fix(select): update component Select

- packages/ui-core/src/components/Tile/Tile.less
- packages/ui-core/src/components/Tile/Tile.test.tsx
- packages/ui-core/src/components/Tile/Tile.tsx
- packages/ui-core/src/components/Tile/__snapshots__/Tile.test.tsx.snap
- packages/ui-core/src/components/Tile/doc/Tile.example.mdx
> fix(tile): fix component shadow

- packages/ui-core/src/components/Carousel/Carousel.less
BREAKING CHANGE: add negative bottom margin for container
> fix(carousel): fix indent without pagination

- packages/ui-core/src/components/Select/Select.test.tsx
- packages/ui-core/src/components/Select/Select.tsx
- packages/ui-core/src/components/Select/__snapshots__/Select.test.tsx.snap
BREAKING CHANGE: items prop reuired and has exact structure in propType
> feat(select): update items prop typings

- packages/ui-shared/src/components/Instructions/Instructions.tsx
- packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
removed activeInstructionItem dependency on instructionItem
> fix(instructions): fix activeInstructionItem class

- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Search/Search.tsx
- packages/ui-core/src/components/Search/doc/Search.example.mdx
- `ui-core / Search`: add optional `disabled` prop
> feat(search): add disabled prop

- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Search/Search.tsx
- packages/ui-core/src/components/Search/__snapshots__/Search.test.tsx.snap
- `ui-core / Search`: fix items container position for prevent `noticeText` to tear input and items
> Search items position fix

- packages/ui-core/src/components/ContentArea/ContentArea.tsx
- `ui-core` / `ContentArea`: fix type variants detection for `innerBackgroundColor` and `outerBackgroundColor` props
> fix(contentarea): fix prop type

- packages/ui-core/src/styles/base.less
- `ui-core` / `base.less`: add and fix some mixins
> feat(ui-core): fix some mixins and variables

- packages/ui-core/src/components/Accordion/Accordion.test.tsx
- packages/ui-core/src/components/Accordion/Accordion.tsx
- packages/ui-core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/ui-core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap
- packages/ui-core/src/components/Calendar/components/Month/Month.test.tsx
- packages/ui-core/src/components/Calendar/components/Month/Month.tsx
- packages/ui-core/src/components/Calendar/components/Month/__snapshots__/Month.test.tsx.snap
- packages/ui-core/src/components/Checkbox/Checkbox.test.tsx
- packages/ui-core/src/components/Checkbox/Checkbox.tsx
- packages/ui-core/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/ui-core/src/components/Tooltip/Tooltip.tsx
- packages/ui-helpers/src/a11y/a11y.test.ts
- packages/ui-helpers/src/a11y/a11y.ts
- packages/ui-helpers/src/index.ts
- packages/ui-shared/src/components/AccordionBox/AccordionBox.tsx
BREAKING CHANGE: changed types of props: onClickAccordion of Accordion and AccordionBox, onChange of Checkbox, onOpen and onClose of Tooltip.
> Add accessibility to accordion, checkbox, calendar

- packages/ui-core/src/components/Tile/Tile.tsx
---
```
"version": "3.0.1"
```
* **tile:** fixed dataAttrs type in tile component ([d380289](https://github.com/MegafonWebLab/megafon-ui/commit/d3802896c57dc112543c73169c04262f58a29f58))
> fix(tile): fixed dataAttrs type in tile component

- packages/ui-shared/src/components/TextWithIcon/TextWithIconItem.tsx
- packages/ui-shared/src/components/TextWithIcon/doc/TextWithIcon.example.mdx
---
```
```
* **textwithiconitem:** add type string[] for text prop ([0df9680](https://github.com/MegafonWebLab/megafon-ui/commit/0df9680e10058ea24783fbc41cbce17e9b2a5594))
> feat(textwithiconitem): add type string[] for text prop

- packages/ui-core/src/components/Banner/Banner.less
- packages/ui-core/src/components/Banner/Banner.tsx
- packages/ui-core/src/components/Banner/__snapshots__/Banner.test.tsx.snap
- packages/ui-core/src/components/Banner/doc/Banner.example.mdx
---
```
"version": "3.0.4"
```
* **banner:** add opacity for slides ([bb403a1](https://github.com/MegafonWebLab/megafon-ui/commit/bb403a1d38fd0c1efd3e1df3ed72ea4e5c772c40))
> feat(banner): add opacity for slides

- packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx
- packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
- packages/ui-shared/src/components/VideoBanner/__snapshots__/VideoBanner.test.tsx.snap
---
```
```
* **videobanner:** added new classes for video ([d8b84a0](https://github.com/MegafonWebLab/megafon-ui/commit/d8b84a003103cf5f66102d354d2625e30a2c0d2a))
> feat(videobanner): added new classes for video

- packages/ui-core/CHANGELOG.md
- packages/ui-core/src/components/Button/Button.less
- packages/ui-core/src/components/ContentArea/ContentArea.less
- packages/ui-core/src/components/Tabs/Tabs.less
- packages/ui-shared/src/components/Breadcrumbs/Breadcrumbs.less
- packages/ui-shared/src/components/Breadcrumbs/Breadcrumbs.tsx
- packages/ui-shared/src/components/Breadcrumbs/doc/Breadcrumbs.example.mdx
- packages/ui-shared/src/components/Breadcrumbs/doc/Breadcrumbs.mdx
- packages/ui-shared/src/components/DownloadLinks/DownloadLink.less
- packages/ui-shared/src/components/Table/Table.less
- **breadcrumbs**: fix api and refactor
- **colors**: fix usage some variables
- **changelog**: fix typo
---
```
"version": "3.0.4"
```
* **colors:** fix colors usage ([f2f59a8](https://github.com/MegafonWebLab/megafon-ui/commit/f2f59a81644c157394817af1531dabb1c0b67b19))
* **breadcrumbs:** allow to pass items as array of JSX elements ([1ca1583](https://github.com/MegafonWebLab/megafon-ui/commit/1ca158390c7c58b5ff117ae8ad16268b043d5ddb))
* **colors:** fix colors usage ([f2f59a8](https://github.com/MegafonWebLab/megafon-ui/commit/f2f59a81644c157394817af1531dabb1c0b67b19))
> fix Breadcrumbs

- packages/ui-core/src/components/ContentArea/ContentArea.less
- packages/ui-core/src/components/ContentArea/ContentArea.tsx
- packages/ui-core/src/components/ContentArea/__snapshots__/ContentArea.test.tsx.snap
- packages/ui-core/src/components/ContentArea/doc/ContentArea.docz.tsx
- packages/ui-core/src/components/ContentArea/doc/ContentArea.example.mdx
- packages/ui-core/src/components/Logo/Logo.tsx
- packages/ui-core/src/components/Paragraph/Paragraph.tsx
- packages/ui-core/src/components/TextLink/TextLink.tsx
- packages/ui-shared/src/components/BenefitsIcons/BenefitsIcons.tsx
- packages/ui-shared/src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
- packages/ui-shared/src/components/ButtonLinkBox/__snapshots__/ButtonLinkBox.test.tsx.snap
- packages/ui-shared/src/components/Card/__snapshots__/Card.test.tsx.snap
- packages/ui-shared/src/components/CardsBox/__snapshots__/CardsBox.test.tsx.snap
- packages/ui-shared/src/components/Container/__snapshots__/Container.test.tsx.snap
- packages/ui-shared/src/components/DownloadLinks/__snapshots__/DownloadLink.test.tsx.snap
- packages/ui-shared/src/components/StoreBanner/StoreBanner.tsx
- packages/ui-shared/src/components/VideoBanner/__snapshots__/VideoBanner.test.tsx.snap
---
```
```
* **colors:** fix colors usage ([f2f59a8](https://github.com/MegafonWebLab/megafon-ui/commit/f2f59a81644c157394817af1531dabb1c0b67b19))
* **components:** better view of default props values ([1817ed5](https://github.com/MegafonWebLab/megafon-ui/commit/1817ed5cd17fd78a0911a89020138f05d7af9833))
* **contentarea:** add 'black' color prop value; deprecate 'default' color prop value; more examples ([e0b0c72](https://github.com/MegafonWebLab/megafon-ui/commit/e0b0c723a37f0e42ccb1c0d30df8ae36e9c82920))
* **banner:** add opacity for slides ([bb403a1](https://github.com/MegafonWebLab/megafon-ui/commit/bb403a …
> fix(contentarea): better color props

- packages/ui-core/src/components/Checkbox/Checkbox.less
---
```
```
* **checkbox:** delete outline focus effect ([ecd98e7](https://github.com/MegafonWebLab/megafon-ui/commit/ecd98e7129ddd305ce6e21c1c98cdacc3670ff92))
> fix(checkbox): delete outline focus effect

- packages/ui-core/src/components/Carousel/Carousel.tsx
- packages/ui-core/src/components/Carousel/__snapshots__/Carousel.test.tsx.snap
---
```
```
* **carousel:** fix data-attribute passing for NavArrow ([af0d26e](https://github.com/MegafonWebLab/megafon-ui/commit/af0d26ef85a19cdb4fd863a45b2c2b2365d9c086))
> feat(carousel): fix data-attribute passing for NavArrow

- packages/ui-icons/src/doc/Icons.tsx
---
```
"version": "1.0.1"
"version": "1.0.2"
```
> docs(icons): remove _direct_url from docs view, names to lowercase

- packages/ui-core/src/components/Carousel/Carousel.tsx
- packages/ui-core/src/components/Carousel/__snapshots__/Carousel.test.tsx.snap
- packages/ui-core/src/components/Checkbox/Checkbox.less
- packages/ui-core/src/components/Tile/Tile.test.tsx
- packages/ui-core/src/components/Tile/Tile.tsx
- packages/ui-core/src/components/Tile/__snapshots__/Tile.test.tsx.snap
- packages/ui-core/src/components/Tile/doc/Tile.example.mdx
- packages/ui-icons/src/doc/Icons.tsx
---
```
"version": "1.0.1"
"version": "1.0.2"
```
* **checkbox:** delete outline focus effect ([ecd98e7](https://github.com/MegafonWebLab/megafon-ui/commit/ecd98e7129ddd305ce6e21c1c98cdacc3670ff92))
* **tile:** delete unnecessary symbol ([1f0ed90](https://github.com/MegafonWebLab/megafon-ui/commit/1f0ed9009ef2cb9e5562f257640a623eceae225e))
* **carousel:** fix data-attribute passing for NavArrow ([af0d26e](https://github.com/MegafonWebLab/megafon-ui/commit/af0d26ef85a19cdb4fd863a45b2c2b2365d9c086))
* **tile:** add target props for link …
> 28.02.2022 release

- packages/ui-core/src/components/Select/Select.test.tsx
- packages/ui-core/src/components/Select/__snapshots__/Select.test.tsx.snap
> test(select): fixed test for Select component

- packages/ui-helpers/src/createTestId.ts
- packages/ui-helpers/src/index.ts
- packages/ui-helpers/src/nestingNameGenerator.test.ts
- packages/ui-helpers/src/nestingNameGenerator.ts
---
```
"version": "2.0.1"
"version": "2.1.0"
"version": "1.0.2"
"version": "1.0.3"
"version": "3.1.2"
```
* **nestingnamegenerator:** added util to form id string for autotest purposes ([4ab5bf1](https://github.com/MegafonWebLab/megafon-ui/commit/4ab5bf1a1da9748e3d783d6140b23376d911b750))
> feat(createtestid): added util to form id string for autotest purposes

- packages/ui-core/src/components/Notification/Notification.less
---
```
```
* **notification:** fix link styles ([9d7e67e](https://github.com/MegafonWebLab/megafon-ui/commit/9d7e67e1f21c9ddb1dc911502a114924c8896a6a))
> fix(notification): fix link styles

- packages/ui-core/src/components/Search/Search.test.tsx
- packages/ui-core/src/components/Search/Search.tsx
---
```
```
* **search:** add onFocus callback ([b6dfdad](https://github.com/MegafonWebLab/megafon-ui/commit/b6dfdadd8dc695d7622bb95443ef6556b4e5d1c6))
> feat(search): add onFocus callback

- packages/ui-helpers/src/nestingNameGenerator.ts
---
```
"version": "2.1.0"
"version": "2.1.1"
"version": "1.1.0"
"version": "1.1.1"
```
* **nestingnamegenerator:** added index incease to element index check ([46085dc](https://github.com/MegafonWebLab/megafon-ui/commit/46085dcd929a5a842206bf57432134f735fd323b))
> fix(nestingnamegenerator): added index increase to element index check

- packages/ui-core/src/components/Select/Select.test.tsx
- packages/ui-shared/src/components/StoreButton/StoreButton.test.tsx
- packages/ui-shared/src/components/StoreButton/StoreButton.tsx
- packages/ui-shared/src/components/StoreButton/__snapshots__/StoreButton.test.tsx.snap
---
```
```
* **storebutton:** fixed test for Select and update type for StoreButton ([8996754](https://github.com/MegafonWebLab/megafon-ui/commit/8996754482e9cf899fdcb0f488c8a9fa1afddd11))
> fix(storebutton): fixed test for Select and update type for StoreButton

- packages/ui-core/src/components/Badges/components/PriceBadge/PriceBadge.less
- packages/ui-core/src/components/Badges/components/PriceBadge/PriceBadge.tsx
- packages/ui-core/src/components/Badges/components/PriceBadge/__snapshots__/PriceBadge.test.tsx.snap
- packages/ui-core/src/components/Badges/components/PromoBadge/PromoBadge.less
- packages/ui-core/src/components/Badges/components/PromoBadge/PromoBadge.tsx
- packages/ui-core/src/components/Badges/components/PromoBadge/doc/PromoBadge.example.mdx
- packages/ui-core/src/components/Badges/components/TimerBadge/Timer/Timer.test.tsx
- packages/ui-core/src/components/Badges/components/TimerBadge/Timer/Timer.tsx
- packages/ui-core/src/components/Badges/components/TimerBadge/Timer/__snapshots__/Timer.test.tsx.snap
- packages/ui-core/src/components/Badges/components/TimerBadge/TimerBadge.less
- packages/ui-core/src/components/Badges/components/TimerBadge/TimerBadge.test.tsx
- packages/ui-core/src/components/Badges/components/TimerBadge/TimerBadge.tsx
- packages/ui-core/src/components/Badges/components/TimerBadge/__snapshots__/TimerBadge.test.tsx.snap
- packages/ui-core/src/components/Badges/components/TimerBadge/doc/TimerBadge.docz.tsx
- packages/ui-core/src/components/Badges/components/TimerBadge/doc/TimerBadge.example.mdx
- packages/ui-core/src/components/Badges/doc/Badges.mdx
---
```
```
* **pricebadge:** fix icon styles ([f5502a0](https://github.com/MegafonWebLab/megafon-ui/commit/f5502a0e28d067694cee4165fe224a38ecf3a15f))
* **badges:** add new component TimerBadge ([82a900b](https://github.com/MegafonWebLab/megafon-ui/commit/82a900b362ca15db30dfdbffbfe299b637cae5b3))
* **promobadge:** add vip type (purple background color) ([51ea858](https://github.com/MegafonWebLab/megafon-ui/commit/51ea8582ff750199166c64681fecae636d30ca18))
> feat(badges): add new component TimerBadge

- src/gatsby-theme-docz/components/NavGroup/index.tsx
> fix(navgroup): fixed autocomplete of search input

- src/gatsby-theme-docz/components/SideBar/SideBar.less
- src/gatsby-theme-docz/components/SideBar/index.tsx
> docs(sidebar): fix theme switcher bug and improve codestyle

- packages/ui-core/src/components/Badges/components/PromoBadge/PromoBadge.less
- packages/ui-core/src/components/Badges/components/PromoBadge/doc/PromoBadge.example.mdx
- packages/ui-core/src/components/Notification/doc/Notification.example.mdx
---
```
"version": "3.4.1"
"version": "3.1.5"
```
* **promobadge:** fixed font color for dark theme ([88781d8](https://github.com/MegafonWebLab/megafon-ui/commit/88781d843e25028a5836b030861939cdf019760d))
> Fix notification demo and promo badge

- packages/ui-shared/src/components/Instructions/Instructions.test.tsx
- packages/ui-shared/src/components/Instructions/Instructions.tsx
- packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
- packages/ui-shared/src/components/Instructions/doc/Instructions.example.mdx
---
```
"version": "2.1.0"
"version": "2.1.1"
"version": "1.1.0"
"version": "1.1.1"
```
* **notification:** fix link styles ([9d7e67e](https://github.com/MegafonWebLab/megafon-ui/commit/9d7e67e1f21c9ddb1dc911502a114924c8896a6a))
* **pricebadge:** fix icon styles ([f5502a0](https://github.com/MegafonWebLab/megafon-ui/commit/f5502a0e28d067694cee4165fe224a38ecf3a15f))
* **storebutton:** fixed test for Select and update type for StoreButton ([8996754](https://github.com/MegafonWebLab/megafon-ui/commit/8996754482e9cf899fdcb0f488c8a9fa1afddd11))
* **badges:** add new …
> feat(instructions): added children for Instruction component

- packages/ui-core/src/components/Badges/components/PromoBadge/PromoBadge.less
- packages/ui-core/src/components/Badges/components/PromoBadge/doc/PromoBadge.example.mdx
- packages/ui-core/src/components/Logo/Logo.less
- packages/ui-core/src/components/Notification/doc/Notification.example.mdx
- packages/ui-core/src/components/Switcher/Switcher.less
- packages/ui-core/src/components/Switcher/Switcher.test.tsx
- packages/ui-core/src/components/Switcher/Switcher.tsx
- packages/ui-core/src/components/Switcher/__snapshots__/Switcher.test.tsx.snap
- packages/ui-core/src/components/Switcher/doc/Switcher.docz.tsx
- packages/ui-core/src/components/Switcher/doc/Switcher.example.mdx
- packages/ui-shared/src/components/Instructions/Instructions.test.tsx
- packages/ui-shared/src/components/Instructions/Instructions.tsx
- packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
- packages/ui-shared/src/components/Instructions/doc/Instructions.example.mdx
- src/gatsby-theme-docz/components/SideBar/SideBar.less
- src/gatsby-theme-docz/components/SideBar/index.tsx
---
```
```
* **logo:** fix img align ([51c81d9](https://github.com/MegafonWebLab/megafon-ui/commit/51c81d9e2edb9cf6b5d245ebb60d8a74f1e8bc1d))
* **promobadge:** fixed font color for dark theme ([88781d8](https://github.com/MegafonWebLab/megafon-ui/commit/88781d843e25028a5836b030861939cdf019760d))
* **switcher:** new props and colors ([adb5f34](https://github.com/MegafonWebLab/megafon-ui/commit/adb5f34e3e0949109445c75dc188d37171637af9))
* **instructions:** added children for Instruction component ([33b5296](https://github.com/MegafonWebLab/megafon-ui/commit/33b5296e7f1ccede197fed5d8887ec871586f0f8))
> 05.04.22 release

- packages/ui-core/src/components/Switcher/Switcher.less
---
```
"version": "3.5.2"
"version": "3.5.3"
"version": "3.2.2"
"version": "3.2.3"
```
* **switcher:** fix safari bugs ([65274bc](https://github.com/MegafonWebLab/megafon-ui/commit/65274bc3c5e7385109afff94a8ff3f712c9af097))
> fix(switcher): fix safari bugs

- packages/ui-core/src/components/Switcher/Switcher.less
- packages/ui-shared/src/components/VideoBanner/VideoBanner.less
- packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx
- packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
- packages/ui-shared/src/components/VideoBanner/__snapshots__/VideoBanner.test.tsx.snap
- packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.example.mdx
---
```
"version": "3.5.2"
"version": "3.5.3"
"version": "3.2.2"
"version": "3.3.0"
```
* **switcher:** fix safari bugs ([65274bc](https://github.com/MegafonWebLab/megafon-ui/commit/65274bc3c5e7385109afff94a8ff3f712c9af097))
* **videobanner:** add proprety for mobile video, use picture for background image ([c21c927](https://github.com/MegafonWebLab/megafon-ui/commit/c21c9278d2ff1e192195a5113d43d50753fd02c5))
> 18.04.2022 release

- packages/ui-core/src/components/Calendar/Calendar.tsx
- packages/ui-core/src/components/Calendar/doc/Calendar.docz.tsx
- packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
---
```
"version": "3.5.3"
"version": "3.5.4"
"version": "3.3.0"
```
* **calendar:** fix go to start day after user choice ([8bbce10](https://github.com/MegafonWebLab/megafon-ui/commit/8bbce102d204f7ea7706158f3e6540c86ed3aada))
> fix(calendar): fix go to start day after user choice

- packages/ui-core/src/components/Tooltip/Tooltip.test.tsx
- packages/ui-core/src/components/Tooltip/Tooltip.tsx
- packages/ui-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- packages/ui-core/src/components/Tooltip/doc/Tooltip.example.mdx
---
```
"version": "3.5.3"
"version": "3.6.0"
"version": "3.3.0"
```
* **tooltip:** added prop isPortal for tooltip ([e6f6d17](https://github.com/MegafonWebLab/megafon-ui/commit/e6f6d1749cd99f065c50bac4eb6a9b3592653f8d))
> feat(tooltip): added prop isPortal for tooltip

- packages/ui-core/src/components/Button/Button.less
- packages/ui-core/src/components/Button/Button.test.tsx
- packages/ui-core/src/components/Button/Button.tsx
- packages/ui-core/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/ui-core/src/components/Button/doc/Button.example.mdx
---
```
"version": "3.6.0"
"version": "3.7.0"
```
* **button:** added extra small size ([a26da46](https://github.com/MegafonWebLab/megafon-ui/commit/a26da4601de7e7c81c40eabf9a87ccdbf18cb790))
> Extra small button size

- packages/ui-shared/src/components/Instructions/Instructions.less
- packages/ui-shared/src/components/Instructions/Instructions.tsx
- packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
---
```
"version": "3.3.3"
```
* **instructions:** remove css prorerty filter for image ([d4ee221](https://github.com/MegafonWebLab/megafon-ui/commit/d4ee22123565b82ec777c1526093a94251e59809))
> fix(instructions): remove css prorerty filter for image

- packages/ui-shared/src/components/Instructions/Instructions.less
- packages/ui-shared/src/components/Instructions/Instructions.tsx
- packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
- packages/ui-shared/src/components/PictureWithDescription/PictureWithDescription.less
---
```
"version": "3.3.3"
```
* **instructions:** remove css prorerty filter for image ([d4ee221](https://github.com/MegafonWebLab/megafon-ui/commit/d4ee22123565b82ec777c1526093a94251e59809))
* **picturewithdescription:** fix clearing indents for first and last element ([d9263e3](https://github.com/MegafonWebLab/megafon-ui/commit/d9263e3670b2d493ec4bf194a2cdd6440d1ea86f))
> 24.05.2022 release

- packages/ui-core/src/components/Tooltip/Tooltip.tsx
- packages/ui-core/src/components/Tooltip/doc/Tooltip.example.mdx
---
```
"version": "3.9.0"
```
* **tooltip:** add portal selector props ([6188832](https://github.com/MegafonWebLab/megafon-ui/commit/6188832e9ba212e7a8182333aba06d77c3e979d6))
> feat(tooltip): add portal selector props

- packages/ui-core/src/components/Select/Select.tsx
- packages/ui-core/src/components/Select/doc/Select.docz.tsx
- packages/ui-core/src/components/Select/doc/Select.example.mdx
- packages/ui-core/src/components/Switcher/Switcher.test.tsx
- packages/ui-core/src/components/Switcher/Switcher.tsx
- packages/ui-core/src/components/Switcher/__snapshots__/Switcher.test.tsx.snap
- packages/ui-core/src/components/Tooltip/Tooltip.tsx
- packages/ui-core/src/components/Tooltip/doc/Tooltip.example.mdx
---
```
"version": "3.9.0"
```
* **select:** fix selected item color when value is zero ([9847095](https://github.com/MegafonWebLab/megafon-ui/commit/98470955ef813504d4bfa4cd4d3aba77b5458446))
* **switcher:** add data-attribute for inner element ([793a022](https://github.com/MegafonWebLab/megafon-ui/commit/793a0224ab957b938e67dd1b4d16c2389a9fb6f8))
* **tooltip:** add portal selector props ([6188832](https://github.com/MegafonWebLab/megafon-ui/commit/6188832e9ba212e7a8182333aba06d77c3e979d6))
> 27.05.2022 release

- packages/ui-shared/src/components/Instructions/Instructions.tsx
- packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
---
```
```
* **instructions:** add swipe to picture ([eb9eb09](https://github.com/MegafonWebLab/megafon-ui/commit/eb9eb0991444e113baf95d2d014d1c690cd1e99a))
> feat(instructions): add swipe to picture

- packages/ui-core/src/components/TextField/TextField.less
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
- packages/ui-core/src/components/TextField/doc/TextField.example.mdx
---
```
"version": "4.0.0-beta.1"
"version": "4.0.0-beta.2"
"version": "4.0.0-beta.1"
"version": "4.0.0-beta.2"
```
* **textfield:** update by new design ([8d11972](https://github.com/MegafonWebLab/megafon-ui/commit/8d11972c73374df0d0a66d4607eb87bb4190e92e))
* **textfield:** add placeholders text by default
label element positon changed
if label prop not setted, label element has text from placeholder (default or in props)
> Update text field

- packages/ui-core/src/components/Tabs/Tabs.less
- packages/ui-core/src/components/Tabs/Tabs.test.tsx
- packages/ui-core/src/components/Tabs/Tabs.tsx
- packages/ui-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- packages/ui-core/src/components/Tabs/doc/Tabs.docz.tsx
- packages/ui-core/src/components/Tabs/doc/Tabs.example.mdx
- packages/ui-shared/src/components/TabsBox/TabsBox.test.tsx
- packages/ui-shared/src/components/TabsBox/__snapshots__/TabsBox.test.tsx.snap
BREAKING CHANGE: hAlign prop removed
size prop small vallue removed
new sizes
---
```
"version": "4.0.0-beta.2"
"version": "4.0.0-beta.3"
"version": "4.0.0-beta.2"
"version": "4.0.0-beta.3"
```
* **tabs:** update by new design ([0a8a175](https://github.com/MegafonWebLab/megafon-ui/commit/0a8a175aa5e30758742c1c663da8a406e30dc3dd))
* **tabs:** new prop autoWidth added
size prop small vallue removed
new sizes
* **tabs:** update by new design ([0a8a175](https://github.com/MegafonWebLab/megafon-ui/commit/0a8a175aa5e30758742c1c663da8a406e30dc3dd))
* **tabs:** new prop autoWidth added
size prop small vallue removed
new sizes
> feat(tabs): update by new design

- packages/ui-core/src/colors/Colors.less
- packages/ui-core/src/components/Accordion/Accordion.less
- packages/ui-core/src/components/Switcher/Switcher.less
- packages/ui-core/src/components/Tabs/Tabs.less
- packages/ui-core/src/components/TextField/TextField.less
- packages/ui-core/src/components/TextField/TextField.test.tsx
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
- packages/ui-core/src/components/TextField/doc/TextField.example.mdx
- packages/ui-core/src/components/TextField/i/textarea-resizer.svg
- packages/ui-core/src/components/Tooltip/Tooltip.less
- packages/ui-core/src/constants/throttleTime.ts
- packages/ui-core/src/styles/base.less
---
```
"version": "4.0.0-beta.3"
"version": "4.0.0-beta.4"
"version": "4.0.0-beta.3"
"version": "4.0.0-beta.4"
```
* **textfield:** fix textarea design bugs ([50cd9c6](https://github.com/MegafonWebLab/megafon-ui/commit/50cd9c6f402318c9e1a45d7da6abd6753aec875f))
* **textfield:** update textarea scroll and resize ([a789d00](https://github.com/MegafonWebLab/megafon-ui/commit/a789d007cbee6e666c6d9e6148aeb267d0f4e5e1))
* **textfield:** add defaultTransitionTiming in less global variables
> fix(textfield): fix textarea design bugs

- packages/ui-core/src/components/Tabs/Tab.tsx
- packages/ui-core/src/components/Tabs/Tabs.test.tsx
- packages/ui-core/src/components/Tabs/Tabs.tsx
- packages/ui-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
---
```
"version": "3.11.0"
"version": "3.12.0"
"version": "3.4.2"
"version": "3.4.3"
```
* **tab:** add data-attribute for inner element ([43e58e1](https://github.com/MegafonWebLab/megafon-ui/commit/43e58e12b8da661020f4b48f55245492c21ad376))
> 28.06.2022 release

- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Search/Search.tsx
- packages/ui-core/src/components/Search/__snapshots__/Search.test.tsx.snap
- packages/ui-core/src/components/Select/Select.less
---
```
"version": "4.0.0-beta.6"
"version": "4.0.0-beta.7"
"version": "4.0.0-beta.7"
"version": "4.0.0-beta.8"
```
* **select:** fix styles ([3e79c68](https://github.com/MegafonWebLab/megafon-ui/commit/3e79c68fecde72e515b7ef52d38d9188e51680f6))
> fix(select): fix styles

- packages/ui-core/src/components/Accordion/Accordion.less
- packages/ui-core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/ui-core/src/components/Header/Header.less
- packages/ui-core/src/components/Header/Header.tsx
- packages/ui-core/src/components/Header/doc/Header.example.mdx
- packages/ui-core/src/components/Notification/Notification.less
- packages/ui-core/src/components/Notification/Notification.tsx
- packages/ui-core/src/components/Notification/__snapshots__/Notification.test.tsx.snap
- packages/ui-core/src/components/Tabs/Tabs.less
- packages/ui-shared/src/components/BenefitsIcons/__snapshots__/BenefitsIcons.test.tsx.snap
- packages/ui-shared/src/components/VideoBanner/__snapshots__/VideoBanner.test.tsx.snap
---
```
"version": "4.0.0-beta.7"
"version": "4.0.0-beta.8"
"version": "4.0.0-beta.8"
"version": "4.0.0-beta.9"
```
* **accordion:** change focus and dark theme styles ([d3e07ea](https://github.com/MegafonWebLab/megafon-ui/commit/d3e07ea6fee0c131e25db1bb558d8b205d201e0c))
* **notification:** change title typography ([f91a60e](https://github.com/MegafonWebLab/megafon-ui/commit/f91a60ee1562626494358ef529321f072ba70890))
* **tabs:** change dark theme and indents styles ([272dfcb](https://github.com/MegafonWebLab/megafon-ui/commit/272dfcbeef750f2f7ae097b46f7d98405cf53a88))
* **header:** add new prop space ([e5bef7c](https://github.com/MegafonWebLab/megafon-ui/commit/e5bef7c8e13c57e477a4c25 …
> fix(accordion): change focus and dark theme styles

- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Select/Select.less
---
```
"version": "4.0.0-beta.8"
"version": "4.0.0-beta.9"
"version": "4.0.0-beta.9"
"version": "4.0.0-beta.10"
```
* **select:** update styles ([b863c8c](https://github.com/MegafonWebLab/megafon-ui/commit/b863c8c94af251d6b3c9ee39124486d7d5db9a58))
> fix(select): update styles

- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Select/Select.less
- packages/ui-core/src/components/Select/Select.tsx
- packages/ui-core/src/components/Select/__snapshots__/Select.test.tsx.snap
---
```
"version": "4.0.0-beta.10"
"version": "4.0.0-beta.11"
"version": "4.0.0-beta.11"
"version": "4.0.0-beta.12"
```
* **search:** changed dropdown list item height ([25ceb63](https://github.com/MegafonWebLab/megafon-ui/commit/25ceb633cdc9922e2a93af919c742b1db82f2f57))
* **select:** fixed label position with empty string value and minor style changes ([f436d5c](https://github.com/MegafonWebLab/megafon-ui/commit/f436d5c65f0aa874d12cd8d1540698644d57a3db))
> Minor search and select fixes

- packages/ui-core/src/components/Carousel/Carousel.tsx
---
```
"version": "3.12.0"
"version": "3.12.1"
"version": "3.4.3"
"version": "3.4.4"
```
* **carousel:** popup input focus ([b1c117a](https://github.com/MegafonWebLab/megafon-ui/commit/b1c117ac1ed560182e61133393ec65f14527958f))
> fix(carousel): popup input focus

- packages/ui-core/src/components/Select/Select.tsx
---
```
"version": "4.0.0-beta.11"
"version": "4.0.0-beta.12"
"version": "4.0.0-beta.12"
"version": "4.0.0-beta.13"
```
* **select:** update value check for undefined ([06f8dbf](https://github.com/MegafonWebLab/megafon-ui/commit/06f8dbfb065eaef7f6151cb88cebffe68d668ef8))
> fix(select): update value check for undefined

- packages/ui-core/src/components/Select/Select.less
- packages/ui-core/src/components/TextField/TextField.test.tsx
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
---
```
"version": "4.0.0-beta.12"
"version": "4.0.0-beta.13"
"version": "4.0.0-beta.13"
"version": "4.0.0-beta.14"
```
> Minor field fixes

- packages/ui-core/package.json
- packages/ui-core/src/components/Banner/Banner.less
- packages/ui-core/src/components/Banner/Banner.test.tsx
- packages/ui-core/src/components/Banner/Banner.tsx
- packages/ui-core/src/components/Banner/__snapshots__/Banner.test.tsx.snap
- yarn.lock
---
```
"version": "3.12.1"
"version": "3.13.0"
"version": "3.4.4"
"version": "3.4.5"
```
* **banner:** add auto height ([c7658fa](https://github.com/MegafonWebLab/megafon-ui/commit/c7658faf335bc26f0a1b816e29b9cca114944691))
> 11.08.2022 release

- packages/ui-core/src/components/TextField/TextField.less
- packages/ui-core/src/components/TextField/TextField.test.tsx
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
- packages/ui-core/src/components/TextField/doc/TextField.example.mdx
---
```
"version": "4.0.0-beta.14"
"version": "4.0.0-beta.15"
"version": "4.0.0-beta.15"
"version": "4.0.0-beta.16"
```
* **textfield:** fix label styles ([080f8fa](https://github.com/MegafonWebLab/megafon-ui/commit/080f8faa3ef8ec954704466dc5b56d0313487787))
* **textfield:** add prop hidePlaceholder ([1c0176e](https://github.com/MegafonWebLab/megafon-ui/commit/1c0176ebdae47d11ac972ada200303500618caf1))
> feat(textfield): add prop hidePlaceholder

- packages/ui-core/src/components/TextField/TextField.less
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
---
```
"version": "4.0.0-beta.15"
"version": "4.0.0-beta.16"
"version": "4.0.0-beta.16"
"version": "4.0.0-beta.17"
```
* **textfield:** fixes permanently visible block after the field ([9cc5184](https://github.com/MegafonWebLab/megafon-ui/commit/9cc5184f7b60a7f7dcfe3f9f49cc3199787a77d7))
> fix(textfield): fixes permanently visible block after the field

- packages/ui-core/src/components/Select/Select.less
- packages/ui-core/src/components/Select/doc/Select.example.mdx
- packages/ui-core/src/components/Tabs/Tabs.less
- packages/ui-core/src/components/Tabs/Tabs.tsx
- packages/ui-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
---
```
"version": "4.0.0-beta.16"
"version": "4.0.0-beta.17"
"version": "4.0.0-beta.17"
"version": "4.0.0-beta.18"
```
* **select:** fix items overflow ([6c795a3](https://github.com/MegafonWebLab/megafon-ui/commit/6c795a35ae27e8100edd6d6ec7456962b8f62a41))
* **tabs:** fix container alignment ([2bd4f31](https://github.com/MegafonWebLab/megafon-ui/commit/2bd4f31fba455a817e9597103c25ca97fe33d2d8))
> Fix select and tabs UI

- packages/ui-core/src/components/Tabs/Tabs.less
- packages/ui-core/src/components/Tabs/Tabs.tsx
- packages/ui-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
---
```
"version": "4.0.0-beta.17"
"version": "4.0.0-beta.18"
"version": "4.0.0-beta.18"
"version": "4.0.0-beta.19"
```
* **tabs:** fix swiper overflow and box-sizing ([bbfb09d](https://github.com/MegafonWebLab/megafon-ui/commit/bbfb09d86223c3dc1f70aaa2a03d108256c3a37d))
> fix(tabs): fix swiper overflow and box-sizing

- packages/ui-core/src/components/Notification/Notification.less
- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Search/Search.tsx
- packages/ui-core/src/components/Search/__snapshots__/Search.test.tsx.snap
- packages/ui-core/src/components/Select/Select.less
- packages/ui-core/src/components/Select/Select.tsx
- packages/ui-core/src/components/Select/__snapshots__/Select.test.tsx.snap
- packages/ui-core/src/components/Select/doc/Select.example.mdx
- packages/ui-core/src/components/Select/doc/Select.props.mdx
---
```
"version": "4.0.0-beta.18"
"version": "4.0.0-beta.19"
"version": "4.0.0-beta.19"
"version": "4.0.0-beta.20"
```
* **notification:** fix bottom gaps ([1427080](https://github.com/MegafonWebLab/megafon-ui/commit/14270809ec97d18dbdf19183111b9034114d9437))
* **search:** add modifier for item paddings ([9df5792](https://github.com/MegafonWebLab/megafon-ui/commit/9df5792d6828f852bed9c1c4e64404667e8d2cd7))
* **select:** add modifier for item paddings ([e5f9735](https://github.com/MegafonWebLab/megafon-ui/commit/e5f97353c9686fba070aad48d3816ec0ce12d5d9))
> fix(notification): fix bottom gaps

- packages/ui-core/src/components/Notification/Notification.less
---
```
"version": "4.0.0-beta.20"
"version": "4.0.0-beta.21"
"version": "4.0.0-beta.21"
"version": "4.0.0-beta.22"
```
* **notification:** fix margin for bottom block ([38d768c](https://github.com/MegafonWebLab/megafon-ui/commit/38d768cb48baf167863b6a143e84909217eff462))
> fix(notification): fix margin for bottom block

- packages/ui-core/src/components/Tabs/Tabs.less
- packages/ui-core/src/components/Tabs/Tabs.tsx
- packages/ui-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- packages/ui-core/src/components/TextField/TextField.test.tsx
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
---
```
"version": "4.0.0-beta.21"
"version": "4.0.0-beta.22"
"version": "4.0.0-beta.22"
"version": "4.0.0-beta.23"
```
* **tabs:** fix swiper arrows ([cac401d](https://github.com/MegafonWebLab/megafon-ui/commit/cac401ddc6ecfde58353827f3a362d8d941d4db8))
* **textfield:** hide verification icon for disabled field ([c950d3c](https://github.com/MegafonWebLab/megafon-ui/commit/c950d3c64f13412e166c5d358b59638bc3c255ae))
> 12950 fix tabs and text field

- packages/ui-core/src/components/Carousel/Carousel.test.tsx
- packages/ui-core/src/components/Carousel/Carousel.tsx
- packages/ui-core/src/components/Carousel/__snapshots__/Carousel.test.tsx.snap
---
```
"version": "3.13.0"
"version": "3.14.0"
"version": "3.4.5"
"version": "3.4.6"
```
* **carousel:** add new prop slideToClickedSlide ([8a43432](https://github.com/MegafonWebLab/megafon-ui/commit/8a4343290f943475c8522adaa3ad2b564c551d83))
> feat(carousel): add new prop slideToClickedSlide

- packages/ui-core/src/components/Badges/components/PromoBadge/PromoBadge.less
- packages/ui-core/src/components/Badges/components/PromoBadge/PromoBadge.tsx
- packages/ui-core/src/components/Badges/components/PromoBadge/doc/PromoBadge.example.mdx
---
```
"version": "3.13.0"
"version": "3.14.0"
"version": "3.4.5"
"version": "3.4.6"
```
* **badge:** add new promo badge type ([8cbe525](https://github.com/MegafonWebLab/megafon-ui/commit/8cbe5253b9d08c19c9343b42cb3920ac259c8844))
> feat(badge): add new promo badge type

- packages/ui-core/src/components/Accordion/Accordion.less
- packages/ui-core/src/components/Notification/Notification.less
- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Select/Select.less
- packages/ui-core/src/components/TextField/TextField.less
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
---
```
"version": "4.0.0-beta.22"
"version": "4.0.0-beta.23"
"version": "4.0.0-beta.23"
"version": "4.0.0-beta.24"
```
* **accordion:** fixes top and bottom padding for title wrap ([ee61836](https://github.com/MegafonWebLab/megafon-ui/commit/ee61836618f6689b87b17f1e13378442a5a7caee))
* **notification:** fixes passive close icon color for colored error type ([6233e9f](https://github.com/MegafonWebLab/megafon-ui/commit/6233e9f16b0a45ff168323fc241f05634e663fd0))
* **search:** fixes hidden placeholder on focus for firefox ([eab12c3](https://github.com/MegafonWebLab/megafon-ui/commit/eab12c34e25236015bffe072ffdbea31535d4d99))
* **select:** fixes hidden placeholder on focus for firefox …
> 14079 visual bugs

- packages/ui-core/src/components/Select/Select.test.tsx
- packages/ui-core/src/components/Select/Select.tsx
- packages/ui-core/src/components/Select/__snapshots__/Select.test.tsx.snap
---
```
"version": "3.14.0"
"version": "3.15.0"
```
* **select:** add class to list-inner element ([44a366c](https://github.com/MegafonWebLab/megafon-ui/commit/44a366ce6b79222f3ef68532c719f5ee13d3d6bf))
> feat(select): add class to list-inner element

- packages/ui-core/src/components/Carousel/doc/Carousel.docz.tsx
- packages/ui-core/src/components/Carousel/doc/Carousel.example.mdx
- packages/ui-core/src/components/Counter/Counter.less
- packages/ui-core/src/components/Tile/doc/Tile.docz.tsx
- packages/ui-core/src/components/Tile/doc/Tile.example.mdx
---
```
"version": "3.14.0"
"version": "3.14.1"
"version": "3.4.6"
"version": "3.4.7"
```
* **counter:** fixes background color that falls outside the element ([7359504](https://github.com/MegafonWebLab/megafon-ui/commit/73595047533cd7bddf75220624e7afcebb2fc94f))
> 14006 fixes components in dark theme

- packages/ui-core/src/components/Tabs/Tabs.test.tsx
- packages/ui-core/src/components/Tabs/Tabs.tsx
- packages/ui-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- packages/ui-core/src/components/TextField/TextField.test.tsx
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
---
```
"version": "4.2.0"
"version": "4.1.0"
"version": "4.1.1"
```
* **tabs:** update prop classes with new keys wrapper and swiperWrapper ([1832aac](https://github.com/MegafonWebLab/megafon-ui/commit/1832aac3a0cdba03c9e74fd4e570be72c4156387))
* **textfield:** update pros classes with new key label ([db2a10d](https://github.com/MegafonWebLab/megafon-ui/commit/db2a10dd23e0ac6634510207202ba86886ae6d61))
> Textfield classes

- packages/ui-core/src/components/Select/Select.less
- packages/ui-core/src/components/Select/Select.test.tsx
- packages/ui-core/src/components/Select/Select.tsx
- packages/ui-core/src/components/Select/__snapshots__/Select.test.tsx.snap
- packages/ui-core/src/components/Select/doc/Select.example.mdx
---
```
"version": "3.15.0"
"version": "3.16.0"
"version": "3.5.2"
```
* **select:** add new props useShortListItems ([cd3ee88](https://github.com/MegafonWebLab/megafon-ui/commit/cd3ee88462e36cf725ab9867f5635c3b89d61511))
> feat(select): add new props useShortListItems

- packages/ui-core/src/components/Tooltip/Tooltip.tsx
---
```
"version": "4.1.1"
```
* **tooltip:** fix touch device controlled trigger ([e983ca8](https://github.com/MegafonWebLab/megafon-ui/commit/e983ca88636990e467b43483b0cf0df06dff8553))
> fix(tooltip): fix touch device controlled trigger

- packages/ui-core/src/components/Select/Select.less
- packages/ui-core/src/components/Select/Select.test.tsx
- packages/ui-core/src/components/Select/Select.tsx
- packages/ui-core/src/components/Select/__snapshots__/Select.test.tsx.snap
- packages/ui-core/src/components/Select/doc/Select.example.mdx
- packages/ui-core/src/components/TextField/TextField.less
- packages/ui-core/src/components/Tooltip/Tooltip.tsx
---
```
"version": "4.1.1"
```
* **textfield:** fix input height in Safari ([b60e1ac](https://github.com/MegafonWebLab/megafon-ui/commit/b60e1acd76dc80b4609b55dc8256eb94e8e8ec0c))
* **tooltip:** fix touch device controlled trigger ([e983ca8](https://github.com/MegafonWebLab/megafon-ui/commit/e983ca88636990e467b43483b0cf0df06dff8553))
* **select:** add new props useShortListItems ([31d1172](https://github.com/MegafonWebLab/megafon-ui/commit/31d1172484ca4c07060ff64eb7f3be692f5dbdec))
> 10.10.2022 release

- packages/ui-core/src/components/Search/Search.test.tsx
- packages/ui-core/src/components/Search/Search.tsx
- packages/ui-core/src/components/Search/__snapshots__/Search.test.tsx.snap
---
```
"version": "4.1.3"
```
* **search:** add new keys for prop classes ([552741b](https://github.com/MegafonWebLab/megafon-ui/commit/552741be627cce59b4ba221645b569ce57e72bd2))
> feat(search): add new keys for prop classes

- packages/ui-core/src/colors/colorsData.tsx
- packages/ui-core/src/components/Switcher/doc/Switcher.example.mdx
---
```
"version": "4.2.0"
```
> chore: replace some "c" chars from latin to cyrillic

- packages/ui-core/src/components/Carousel/Carousel.tsx
- packages/ui-core/src/components/Carousel/usePrevious.ts
- packages/ui-core/src/components/Tabs/Tabs.tsx
---
```
"version": "4.2.2"
```
* **carousel:** change navigation view after change slides count ([7b300eb](https://github.com/MegafonWebLab/megafon-ui/commit/7b300eb9c6f805c3b425104a17f437b3b8a520c5))
* **tabs:** change tabs list structure for correct underline width ([ab87ab2](https://github.com/MegafonWebLab/megafon-ui/commit/ab87ab2e23b3db7620ea0fd83c58bdc8f51ab0ae))
> Fix tabs index

- packages/ui-core/src/components/Switcher/Switcher.less
---
```
"version": "4.2.2"
```
> style(switcher): remove selection on tap

- packages/ui-core/src/components/Search/Search.less
---
```
"version": "4.2.2"
```
* **search:** fix input field font-size for all browsers ([739f3b0](https://github.com/MegafonWebLab/megafon-ui/commit/739f3b02a2dbf8abc6ad430e43272a5bae4d9cf9))
> fix(search): fix input field font-size for all browsers

- .github/workflows/build-docs.yaml
- .github/workflows/ci.yaml
> ci(github): update node version to 16 for build-docs.yaml and ci.yaml

- packages/ui-core/CHANGELOG.md
- packages/ui-shared/CHANGELOG.md
> chore: add missing breaking changes info to CHANGELOG

- packages/ui-core/src/components/Notification/Notification.tsx
- packages/ui-core/src/components/Notification/doc/Notification.docz.tsx
- packages/ui-core/src/components/Notification/doc/Notification.example.mdx
- packages/ui-helpers/src/baseConvertConfig.tsx
- packages/ui-helpers/src/index.ts
- packages/ui-shared/src/components/ButtonBanner/ButtonBanner.tsx
- packages/ui-shared/src/components/ButtonBanner/doc/ButtonBanner.docz.tsx
- packages/ui-shared/src/components/ButtonBanner/doc/ButtonBanner.example.mdx
- packages/ui-shared/src/components/Card/Card.tsx
- packages/ui-shared/src/components/Card/doc/Card.docz.tsx
- packages/ui-shared/src/components/Card/doc/Card.example.mdx
- packages/ui-shared/src/components/StoreBanner/StoreBanner.tsx
- packages/ui-shared/src/components/StoreBanner/doc/StoreBanner.docz.tsx
- packages/ui-shared/src/components/StoreBanner/doc/StoreBanner.example.mdx
- packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
- packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.docz.tsx
- packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.example.mdx
---
```
"version": "2.2.0"
"version": "2.3.0"
"version": "2.2.0"
"version": "2.2.1"
```
* **notification:** allow using html: br, &nbsp, font color, a href in title plus b in text ([1661b7b](https://github.com/MegafonWebLab/megafon-ui/commit/1661b7b602532594ed4d1398d9f70870b1e4d852))
* **config:** add common config for convert function ([92e2661](https://github.com/MegafonWebLab/megafon-ui/commit/92e266156c3fcae31827c9e67f7bc6f440ca498e))
* **buttonbunner:** allow using html: br, &nbsp, font color, a href in …
> feat(*): allow using html tag in title of buttonBunner, notification, card, storeBunner

- packages/ui-core/src/components/Accordion/Accordion.test.tsx
- packages/ui-core/src/components/Accordion/Accordion.tsx
- packages/ui-core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/ui-shared/src/components/AccordionBox/AccordionBox.tsx
---
```
```
* **accordion:** fix dataAttrs props ([bb6e71c](https://github.com/MegafonWebLab/megafon-ui/commit/bb6e71cf36687fdcfb41a9ee40a27e0fdb21940b))
* **accordionbox:** fix dataAttrs props ([46e0b05](https://github.com/MegafonWebLab/megafon-ui/commit/46e0b05c3a18d9a730c360a59f4dfef78013827d))
> 13570 accordion tests

- packages/ui-core/src/components/Caption/Caption.less
Change font-weight for view variant is medium
---
```
```
> style(caption): change font-weight

- packages/ui-core/src/components/Badges/components/PriceBadge/PriceBadge.test.tsx
- packages/ui-core/src/components/Badges/components/PriceBadge/__snapshots__/PriceBadge.test.tsx.snap
- packages/ui-core/src/components/Badges/components/PromoBadge/PromoBadge.test.tsx
- packages/ui-core/src/components/Badges/components/PromoBadge/__snapshots__/PromoBadge.test.tsx.snap
- packages/ui-core/src/components/Badges/components/TimerBadge/Timer/Timer.test.tsx
- packages/ui-core/src/components/Badges/components/TimerBadge/Timer/__snapshots__/Timer.test.tsx.snap
- packages/ui-core/src/components/Badges/components/TimerBadge/TimerBadge.test.tsx
- packages/ui-core/src/components/Badges/components/TimerBadge/TimerBadge.tsx
- packages/ui-core/src/components/Badges/components/TimerBadge/__snapshots__/TimerBadge.test.tsx.snap
---
```
```
* **timerbadge:** add iconContainer to dataAttrs prop ([fa9b094](https://github.com/MegafonWebLab/megafon-ui/commit/fa9b094b209705c448de63fe0cfbfe52764e6709))
> 13575 badges

- packages/ui-core/src/components/Banner/Banner.test.tsx
- packages/ui-core/src/components/Banner/BannerDot.test.tsx
- packages/ui-core/src/components/Banner/BannerDot.tsx
- packages/ui-core/src/components/Banner/__snapshots__/Banner.test.tsx.snap
- packages/ui-core/src/components/Banner/__snapshots__/BannerDot.test.tsx.snap
- packages/ui-core/src/components/Tabs/Tabs.less
- packages/ui-core/src/components/Tabs/Tabs.tsx
- packages/ui-core/src/components/Tabs/doc/Tabs.example.mdx
- packages/ui-core/src/components/TextField/TextField.less
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
- packages/ui-core/src/components/TextField/doc/TextField.example.mdx
- packages/ui-shared/src/components/AccordionBox/AccordionBox.less
- packages/ui-shared/src/components/AccordionBox/doc/AccordionBox.example.mdx
---
```
```
* **textfield:** fix right padding with hideIcon prop ([c2aeffd](https://github.com/MegafonWebLab/megafon-ui/commit/c2aeffd1e4c94c97aac23128b9f1ccff4ead9a81))
* **tabs:** add gray color to tabColorTheme prop ([9d01119](https://github.com/MegafonWebLab/megafon-ui/commit/9d01119aef6ee6ef26e02c7b22efd17cb8a1147a))
* **accordionbox:** add missing margin for group of components ([e20da93](https://github.com/MegafonWebLab/megafon-ui/commit/e20da9336f664b526671e5950d319e8ef4dbd946))
> 07.11.2022 release

- packages/ui-core/src/components/Header/doc/Header.example.mdx
- packages/ui-core/src/components/List/doc/List.example.mdx
- packages/ui-core/src/components/Tabs/doc/Tabs.example.mdx
- packages/ui-shared/src/components/BenefitsPictures/doc/BenefitsPictures.example.mdx
- packages/ui-shared/src/components/ButtonLinkBox/doc/ButtonLinkBox.example.mdx
- packages/ui-shared/src/components/Card/doc/Card.example.mdx
- packages/ui-shared/src/components/Container/doc/Container.example.mdx
- packages/ui-shared/src/components/TitleDescriptionBox/doc/TitleDescriptionBox.example.mdx
> docs: replace prop hAlign to align in some components

- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Select/Select.less
- packages/ui-core/src/components/Tabs/Tabs.tsx
- packages/ui-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- packages/ui-core/src/components/TextField/TextField.less
---
```
"version": "4.4.2"
```
* **search:** fix scrollbar styles ([c8df5df](https://github.com/MegafonWebLab/megafon-ui/commit/c8df5df9787984a5eb9556b786ab8a6bee75dcb7))
* **select:** fix scrollbar styles ([15fdd41](https://github.com/MegafonWebLab/megafon-ui/commit/15fdd4170b600b8dad5f6144dadb86ae1d1e7cc0))
* **tabs:** update resize ([710895f](https://github.com/MegafonWebLab/megafon-ui/commit/710895f4c2f0899fb41ac08e7dde7b1636c24ed9))
* **textfield:** fix scrollbar styles ([8205a34](https://github.com/MegafonWebLab/megafon-ui/commit/8205a345dfe254a8f46fe4b1023f18761a5a9d29))
**Note:** Version bump only for package …
> Fix markup bugs

- packages/ui-core/src/components/Accordion/Accordion.less
---
```
"version": "4.4.2"
```
> style(accordion): fix for safari

- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Search/Search.tsx
- packages/ui-core/src/components/Search/__snapshots__/Search.test.tsx.snap
- packages/ui-core/src/components/Search/doc/Search.example.mdx
---
```
"version": "4.8.0"
```
* **search:** show placeholder without label ([b059216](https://github.com/MegafonWebLab/megafon-ui/commit/b05921619514787698e82d27644702d231829c50))
> fix(search): show placeholder without label

- packages/ui-core/src/components/Caption/Caption.test.tsx
- packages/ui-core/src/components/Caption/__snapshots__/Caption.test.tsx.snap
- packages/ui-core/src/components/Checkbox/Checkbox.test.tsx
- packages/ui-core/src/components/Checkbox/Checkbox.tsx
- packages/ui-core/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
---
```
"version": "4.8.2"
```
> 13705 caption checkbox

- packages/ui-core/src/components/List/List.less
- packages/ui-core/src/components/List/List.test.tsx
- packages/ui-core/src/components/List/List.tsx
- packages/ui-core/src/components/List/__snapshots__/List.test.tsx.snap
- packages/ui-core/src/components/List/doc/List.example.mdx
---
```
"version": "4.8.2"
```
> style(list): edit list align style

- package.json
> chore: add missing source-map dependency

- package.json
- yarn.lock
> chore: fix yarn.lock dependencies

- packages/ui-core/src/components/Tooltip/Tooltip.less
- packages/ui-core/src/components/Tooltip/Tooltip.tsx
- packages/ui-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- packages/ui-core/src/components/Tooltip/doc/Tooltip.example.mdx
---
```
"version": "4.8.2"
"version": "4.8.3"
```
* **tooltip:** fix close button margin and arrow position ([db99274](https://github.com/MegafonWebLab/megafon-ui/commit/db99274ab17fe58621aaaf1ba7d85bba6afc5e05))
> style(tooltip): add adaptive styles for tooltip

- packages/ui-core/src/components/Link/Link.test.tsx
- packages/ui-core/src/components/Link/__snapshots__/Link.test.tsx.snap
- packages/ui-core/src/components/Logo/Logo.test.tsx
- packages/ui-core/src/components/Logo/Logo.tsx
- packages/ui-core/src/components/Logo/__snapshots__/Logo.test.tsx.snap
- packages/ui-core/src/components/NavArrow/NavArrow.test.tsx
- packages/ui-core/src/components/NavArrow/NavArrow.tsx
- packages/ui-core/src/components/NavArrow/__snapshots__/NavArrow.test.tsx.snap
- packages/ui-core/src/components/Paragraph/Paragraph.test.tsx
- packages/ui-core/src/components/Paragraph/__snapshots__/Paragraph.test.tsx.snap
---
```
"version": "4.9.0"
"version": "4.5.4"
```
> 13895 tests

- packages/ui-shared/src/components/VideoBlock/VideoBlock.test.tsx
- packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
- packages/ui-shared/src/components/VideoBlock/__snapshots__/VideoBlock.test.tsx.snap
- packages/ui-shared/src/components/VideoBlock/doc/VideoBlock.example.mdx
---
```
```
* **videoblock:** add playsinline prop ([c383928](https://github.com/MegafonWebLab/megafon-ui/commit/c383928473596bb962e68a15125fa9574bce4a64))
> feat(videoblock): add playsinline prop

- packages/ui-core/src/components/Counter/Counter.test.tsx
- packages/ui-core/src/components/Counter/Counter.tsx
- packages/ui-core/src/components/Counter/__snapshots__/Counter.test.tsx.snap
- packages/ui-core/src/components/Link/Link.test.tsx
- packages/ui-core/src/components/Link/__snapshots__/Link.test.tsx.snap
- packages/ui-core/src/components/Logo/Logo.test.tsx
- packages/ui-core/src/components/Logo/Logo.tsx
- packages/ui-core/src/components/Logo/__snapshots__/Logo.test.tsx.snap
- packages/ui-core/src/components/NavArrow/NavArrow.test.tsx
- packages/ui-core/src/components/NavArrow/NavArrow.tsx
- packages/ui-core/src/components/NavArrow/__snapshots__/NavArrow.test.tsx.snap
- packages/ui-core/src/components/Paragraph/Paragraph.test.tsx
- packages/ui-core/src/components/Paragraph/__snapshots__/Paragraph.test.tsx.snap
- packages/ui-shared/src/components/TextWithIcon/TextWithIconItem.test.tsx
- packages/ui-shared/src/components/TextWithIcon/TextWithIconItem.tsx
- packages/ui-shared/src/components/TextWithIcon/__snapshots__/TextWithIconItem.test.tsx.snap
- packages/ui-shared/src/components/TextWithIcon/doc/TextWithIcon.example.mdx
- packages/ui-shared/src/components/VideoBlock/VideoBlock.test.tsx
- packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
- packages/ui-shared/src/components/VideoBlock/__snapshots__/VideoBlock.test.tsx.snap
- packages/ui-shared/src/components/VideoBlock/doc/VideoBlock.example.mdx
---
```
"version": "4.9.0"
```
* **textwithicon:** fix playground ([44c4b6a](https://github.com/MegafonWebLab/megafon-ui/commit/44c4b6ad323a88f48d3b79191e3be4c44fa2ac14))
* **textwithiconitem:** add example and fix text ([3db8692](https://github.com/MegafonWebLab/megafon-ui/commit/3db869242615caacf1101e4fcff1877ee43c9c95))
* **textwithiconitem:** add render html and classes ([74e21bc](https://github.com/MegafonWebLab/megafon-ui/commit/74e21bcb78e3f4764ceb58d8fa102b6b000c5ae2))
* **videoblock:** add playsinline prop …
> 06.12.2022 release

- packages/ui-core/src/components/Checkbox/Checkbox.less
---
```
"version": "4.9.2"
"version": "4.6.1"
```
* **checkbox:** update styles ([91c2c01](https://github.com/MegafonWebLab/megafon-ui/commit/91c2c01871ca3bae54f4c7204f5953341a7e80cc))
> fix(checkbox): update styles

- packages/ui-core/src/components/Tile/Tile.test.tsx
- packages/ui-core/src/components/Tile/Tile.tsx
- packages/ui-core/src/components/Tile/__snapshots__/Tile.test.tsx.snap
---
```
"version": "4.6.1"
```
* **tile:** added rel property ([8b2c8bf](https://github.com/MegafonWebLab/megafon-ui/commit/8b2c8bf8a3ddcba83b085f028460fdc1d14559d3))
> feat(tile): added rel property

- packages/ui-core/src/components/Accordion/Accordion.test.tsx
- packages/ui-core/src/components/Accordion/Accordion.tsx
- packages/ui-core/src/components/Accordion/doc/Accordion.example.mdx
- packages/ui-core/src/components/Link/Link.test.tsx
- packages/ui-core/src/components/Link/Link.tsx
- packages/ui-core/src/components/TextLink/TextLink.test.tsx
- packages/ui-core/src/components/TextLink/TextLink.tsx
- packages/ui-core/src/components/TextLink/__snapshots__/TextLink.test.tsx.snap
- packages/ui-shared/src/components/AccordionBox/AccordionBox.tsx
- packages/ui-shared/src/components/Breadcrumbs/Breadcrumbs.less
- packages/ui-shared/src/components/Breadcrumbs/Breadcrumbs.test.tsx
- packages/ui-shared/src/components/Breadcrumbs/Breadcrumbs.tsx
- packages/ui-shared/src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
- packages/ui-shared/src/components/Breadcrumbs/components/BreadcrumbsItem.less
- packages/ui-shared/src/components/Breadcrumbs/components/BreadcrumbsItem.test.tsx
- packages/ui-shared/src/components/Breadcrumbs/components/BreadcrumbsItem.tsx
- packages/ui-shared/src/components/Breadcrumbs/components/__snapshots__/BreadcrumbsItem.test.tsx.snap
- packages/ui-shared/src/components/Breadcrumbs/doc/Breadcrumbs.example.mdx
- packages/ui-shared/src/components/Breadcrumbs/doc/Breadcrumbs.props.mdx
- packages/ui-shared/src/components/FaqWrapper/FaqWrapper.test.tsx
- packages/ui-shared/src/components/FaqWrapper/FaqWrapper.tsx
- packages/ui-shared/src/components/FaqWrapper/__snapshots__/FaqWrapper.test.tsx.snap
- packages/ui-shared/src/components/FaqWrapper/doc/FaqWrapper.example.mdx
- packages/ui-shared/src/components/FaqWrapper/doc/FaqWrapper.mdx
- packages/ui-shared/src/components/PageTitle/PageTitle.test.tsx
- packages/ui-shared/src/components/PageTitle/PageTitle.tsx
- packages/ui-shared/src/components/PageTitle/__snapshots__/PageTitle.test.tsx.snap
- packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx
- packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
- packages/ui-shared/src/components/VideoBanner/__snapshots__/VideoBanner.test.tsx.snap
---
```
```
* **accordion:** add optional microdata attributes ([a67df13](https://github.com/MegafonWebLab/megafon-ui/commit/a67df131fe8a47ac4b8574784135765e4e3659bc))
* **link:** add itemprop attribute ([1243b6a](https://github.com/MegafonWebLab/megafon-ui/commit/1243b6a2b65dc157dff82d9943ee08f8f148c688))
* **textlink:** add itemprop attribute ([77a5294](https://github.com/MegafonWebLab/megafon-ui/commit/77a529437cb73cb927381d62f88f48b2b4cc5f0c))
* **accordionbox:** add isMicrodata prop ([07cce83](https://github.com/MegafonWebLab/megafon-ui/commit/07cce8335c062687c4d1dc33b3569c89d6388181))
* **breadcrumbs:** …
> 13917 microdata

- packages/ui-core/src/components/Checkbox/Checkbox.less
---
```
```
* **checkbox:** light checked bg-color ([5190a07](https://github.com/MegafonWebLab/megafon-ui/commit/5190a07b532b7b306a5c9de9f3586a3afaa230df))
> fix(checkbox): light checked bg-color

- packages/ui-core/src/components/Carousel/Carousel.test.tsx
- packages/ui-core/src/components/Carousel/__snapshots__/Carousel.test.tsx.snap
- packages/ui-core/src/components/Carousel/doc/Carousel.docz.tsx
- packages/ui-core/src/components/List/ListItem.test.tsx
- packages/ui-core/src/components/List/__snapshots__/ListItem.test.tsx.snap
- packages/ui-core/src/components/Preloader/Preloader.test.tsx
- packages/ui-core/src/components/Preloader/__snapshots__/Preloader.test.tsx.snap
> 13909 tests

- packages/ui-core/src/components/TextField/TextField.less
- packages/ui-core/src/components/TextField/TextField.tsx
- packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
---
```
```
* **textfield:** fix dynamic height of textarea ([730b594](https://github.com/MegafonWebLab/megafon-ui/commit/730b5947358ada3c7d99e4849dc1563d2b752b32))
> fix(textfield): fix dynamic height of textarea

- packages/ui-core/src/components/RadioButton/RadioButton.less
---
```
```
* **radiobutton:** update design ([2072f43](https://github.com/MegafonWebLab/megafon-ui/commit/2072f431efedfbacb679d7b39b378181cb038b83))
> fix(radiobutton): update design

- packages/ui-core/src/colors/colorsData.tsx
- packages/ui-core/src/components/Button/Button.less
- packages/ui-core/src/components/Button/Button.tsx
- packages/ui-core/src/components/Button/doc/Button.example.mdx
- packages/ui-core/src/styles/colors.css
- packages/ui-core/src/styles/colorsDark.css
- packages/ui-helpers/src/applyTheme.ts
---
```
"version": "2.3.1"
"version": "2.4.0"
"version": "2.4.1"
"version": "2.4.2"
"version": "4.8.0"
```
* **button:** add soft green and soft purple button ([5f3be76](https://github.com/MegafonWebLab/megafon-ui/commit/5f3be76ecbb8e4549ac742aa9994d7f4e4b66ac7))
* **button:** add soft green and soft purple button ([5f3be76](https://github.com/MegafonWebLab/megafon-ui/commit/5f3be76ecbb8e4549ac742aa9994d7f4e4b66ac7))
> feat(button): add soft green and soft purple theme button

- packages/ui-shared/src/components/Steps/Steps.test.tsx
- packages/ui-shared/src/components/Steps/Steps.tsx
- packages/ui-shared/src/components/Steps/StepsItem.tsx
- packages/ui-shared/src/components/Steps/__snapshots__/Steps.test.tsx.snap
- packages/ui-shared/src/components/Steps/doc/Steps.docz.tsx
- packages/ui-shared/src/components/Steps/doc/Steps.example.mdx
---
```
"version": "4.8.0"
```
* **step:** added className and render html ([d6eceda](https://github.com/MegafonWebLab/megafon-ui/commit/d6eceda42f9d20fe4adf948f900f77bfeaa951d9))
> feat(step): added className and render html

- packages/ui-shared/src/components/Instructions/Instructions.tsx
- packages/ui-shared/src/components/Instructions/doc/Instructions.example.mdx
---
```
"version": "4.8.0"
"version": "4.9.0"
```
* **instructions:** added convert to html for title and text ([81d43b2](https://github.com/MegafonWebLab/megafon-ui/commit/81d43b2b3d3b14f0caaba287b26392a55936bc6c))
> feat(instructions): added convert to html for title and text

- README.md
> docs(readme): remove link

- packages/ui-shared/src/components/VideoBlock/VideoBlock.less
- packages/ui-shared/src/components/VideoBlock/VideoBlock.test.tsx
- packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
- packages/ui-shared/src/components/VideoBlock/__snapshots__/VideoBlock.test.tsx.snap
- packages/ui-shared/src/components/VideoBlock/doc/VideoBlock.example.mdx
---
```
```
* **videoblock:** add props fixWhiteVideoBackground ([0bd622a](https://github.com/MegafonWebLab/megafon-ui/commit/0bd622af335fff8f6ee43fb53cdc9d162ef906c6))
> feat(videoblock): add props fixWhiteVideoBackground

- packages/ui-core/src/components/Button/Button.less
- packages/ui-core/src/components/Button/Button.tsx
- packages/ui-core/src/components/Button/doc/Button.docz.tsx
- packages/ui-core/src/components/Button/doc/Button.example.mdx
---
```
"version": "4.11.1"
"version": "4.11.2"
"version": "4.9.2"
```
* **button:** fixed styles ([1fc2ad3](https://github.com/MegafonWebLab/megafon-ui/commit/1fc2ad37f0b8b57e992f764802f11316b95539d3))
> fix(button): fixed styles

- packages/ui-core/src/components/Tooltip/Tooltip.less
- packages/ui-core/src/components/Tooltip/Tooltip.tsx
- packages/ui-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
---
```
"version": "4.11.1"
"version": "4.11.2"
"version": "4.9.2"
```
* **tooltip:** fix margins ([5572397](https://github.com/MegafonWebLab/megafon-ui/commit/55723976459d58ecf131e9fe5aee570c9871b1d2))
> fix(tooltip): fix margins

- packages/ui-core/src/components/Button/Button.less
- packages/ui-core/src/components/Button/Button.tsx
- packages/ui-core/src/components/Button/doc/Button.docz.tsx
- packages/ui-core/src/components/Button/doc/Button.example.mdx
- packages/ui-core/src/components/Tooltip/Tooltip.less
- packages/ui-core/src/components/Tooltip/Tooltip.tsx
- packages/ui-core/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- packages/ui-shared/src/components/VideoBlock/VideoBlock.less
- packages/ui-shared/src/components/VideoBlock/VideoBlock.test.tsx
- packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
- packages/ui-shared/src/components/VideoBlock/__snapshots__/VideoBlock.test.tsx.snap
- packages/ui-shared/src/components/VideoBlock/doc/VideoBlock.example.mdx
---
```
"version": "4.11.1"
"version": "4.11.2"
```
* **button:** fixed styles ([1fc2ad3](https://github.com/MegafonWebLab/megafon-ui/commit/1fc2ad37f0b8b57e992f764802f11316b95539d3))
* **tooltip:** fix margins ([5572397](https://github.com/MegafonWebLab/megafon-ui/commit/55723976459d58ecf131e9fe5aee570c9871b1d2))
* **videoblock:** add props fixWhiteVideoBackground ([0bd622a](https://github.com/MegafonWebLab/megafon-ui/commit/0bd622af335fff8f6ee43fb53cdc9d162ef906c6))
> 23.01.2023 release

- packages/ui-core/src/components/Notification/Notification.test.tsx
- packages/ui-core/src/components/Notification/Notification.tsx
- packages/ui-core/src/components/Notification/__snapshots__/Notification.test.tsx.snap
---
```
"version": "4.11.2"
"version": "4.11.3"
```
> test(notification): migrate tests to react-testing-library

- packages/ui-shared/src/components/CardsBox/CardsBox.test.tsx
- packages/ui-shared/src/components/CardsBox/CardsBox.tsx
- packages/ui-shared/src/components/CardsBox/__snapshots__/CardsBox.test.tsx.snap
- packages/ui-shared/src/components/CardsBox/doc/CardsBox.example.mdx
---
```
```
* **cardsbox:** add prop hGridAlign ([883d12b](https://github.com/MegafonWebLab/megafon-ui/commit/883d12b3447659787d8aa3f61e734e8cb1b03656))
> feat(cardsbox): add prop gridHAlign

- packages/ui-icons/src/System/24/BarCode_24.svg
---
```
"version": "4.11.3"
"version": "4.11.4"
"version": "2.5.0"
"version": "2.6.0"
"version": "4.11.1"
```
* **icons:** add barCode_24 system icon ([957e4cc](https://github.com/MegafonWebLab/megafon-ui/commit/957e4ccb11eb671d3df93a93b91b8615e71e98e2))
> feat(icons): add BarCode_24 system icon

- packages/ui-core/src/components/RadioButton/RadioButton.test.tsx
- packages/ui-core/src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
> test(radiobutton): migrate tests to react-testing-library

- packages/ui-core/src/components/RadioButton/RadioButton.test.tsx
- packages/ui-core/src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
- packages/ui-icons/src/System/24/BarCode_24.svg
- packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
- packages/ui-shared/src/components/BenefitsPictures/__snapshots__/BenefitPictures.test.tsx.snap
- packages/ui-shared/src/components/BenefitsPictures/doc/BenefitsPictures.docz.tsx
- packages/ui-shared/src/components/BenefitsPictures/types.ts
- packages/ui-shared/src/components/Card/Card.test.tsx
- packages/ui-shared/src/components/Card/Card.tsx
- packages/ui-shared/src/components/Card/__snapshots__/Card.test.tsx.snap
- packages/ui-shared/src/components/Instructions/Instructions.test.tsx
- packages/ui-shared/src/components/Instructions/Instructions.tsx
- packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
- packages/ui-shared/src/components/PictureWithDescription/PictureWithDescription.test.tsx
- packages/ui-shared/src/components/PictureWithDescription/PictureWithDescription.tsx
- packages/ui-shared/src/components/PictureWithDescription/__snapshots__/PictureWithDescription.test.tsx.snap
- packages/ui-shared/src/components/TextBox/TextBoxPicture.test.tsx
- packages/ui-shared/src/components/TextBox/TextBoxPicture.tsx
- packages/ui-shared/src/components/TextBox/__snapshots__/TextBoxPicture.test.tsx.snap
- packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx
- packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
- packages/ui-shared/src/components/VideoBanner/__snapshots__/VideoBanner.test.tsx.snap
---
```
"version": "4.11.3"
"version": "4.11.4"
"version": "2.5.0"
"version": "2.6.0"
```
* **icons:** add barCode_24 system icon ([957e4cc](https://github.com/MegafonWebLab/megafon-ui/commit/957e4ccb11eb671d3df93a93b91b8615e71e98e2))
* **benefitpictures:** add alt prop for images ([3fd19e7](https://github.com/MegafonWebLab/megafon-ui/commit/3fd19e718068db8d418adccbb1812e4e8dd6e090))
* **card:** add alt prop for image ([a56a159](https://github.com/MegafonWebLab/megafon-ui/commit/a56a1595b1114e63aa80d9f8976bfb8d54b871db))
* **instructions:** add alt prop for images …
> 06.02.2023 release

- packages/ui-core/src/components/Select/Select.test.tsx
- packages/ui-core/src/components/Select/Select.tsx
- packages/ui-core/src/components/Select/__snapshots__/Select.test.tsx.snap
---
```
"version": "4.11.4"
"version": "4.11.5"
"version": "4.12.1"
```
> test(select): rewrite tests using testing-library

- packages/ui-core/src/components/TextLink/TextLink.test.tsx
- packages/ui-core/src/components/TextLink/__snapshots__/TextLink.test.tsx.snap
> test(textlink): migrate tests to react-testing-library

- packages/ui-core/src/components/Tile/Tile.test.tsx
- packages/ui-core/src/components/Tile/__snapshots__/Tile.test.tsx.snap
> test(tile): migrate tests to react-testing-library

- packages/ui-core/src/components/Search/Search.test.tsx
- packages/ui-core/src/components/Search/Search.tsx
- packages/ui-core/src/components/Search/__snapshots__/Search.test.tsx.snap
---
```
"version": "4.12.1"
"version": "4.13.0"
"version": "4.13.1"
```
> test(search): migrate tests to react-testing-library

- packages/ui-core/src/components/Carousel/Carousel.less
- packages/ui-core/src/components/Carousel/Carousel.test.tsx
- packages/ui-core/src/components/Carousel/Carousel.tsx
- packages/ui-core/src/components/Carousel/doc/Carousel.example.mdx
- packages/ui-core/src/components/Carousel/useGradient.ts
- packages/ui-core/src/components/NavArrow/NavArrow.less
---
```
"version": "4.13.0"
"version": "4.13.0"
"version": "4.13.1"
```
* **carousel:** add property for gradient ([9900586](https://github.com/MegafonWebLab/megafon-ui/commit/99005866bc54d60f3447742f129f036391fb3a68))
> 14310 edit carousel style

- packages/ui-core/src/components/Carousel/Carousel.less
---
```
"version": "4.13.0"
"version": "4.13.1"
"version": "4.13.2"
```
* **carousel:** fix z-index of naw arrow ([b6b1ae1](https://github.com/MegafonWebLab/megafon-ui/commit/b6b1ae18e8641d8168bc97598df62a1ce0eac1f4))
> feat(carousel): fix z-index of naw arrow

- packages/ui-core/src/components/Button/Button.tsx
- packages/ui-core/src/components/Preloader/Preloader.test.tsx
- packages/ui-core/src/components/Preloader/Preloader.tsx
- packages/ui-core/src/components/Preloader/doc/Preloader.example.mdx
---
```
"version": "4.13.0"
"version": "4.13.1"
"version": "4.13.2"
```
* **button:** disable delay for loader ([a19c599](https://github.com/MegafonWebLab/megafon-ui/commit/a19c599f884d5dc9d485c56c6c7914e76d1c3fb6))
* **preloader:** add new prop hasDelay ([356305d](https://github.com/MegafonWebLab/megafon-ui/commit/356305d70451d38e91e638970eb9b597cac86ea7))
> Button loader

- packages/ui-shared/src/components/Property/Property.less
- packages/ui-shared/src/components/Property/Property.test.tsx
- packages/ui-shared/src/components/Property/Property.tsx
- packages/ui-shared/src/components/Property/__snapshots__/Property.test.tsx.snap
- packages/ui-shared/src/components/Property/doc/Property.example.mdx
---
```
"version": "4.13.2"
```
* **property:** add prop disableBorderTop ([dd74ac7](https://github.com/MegafonWebLab/megafon-ui/commit/dd74ac7e4391cbaf947b05b409ca82b068c1a490))
> feat(property): add prop disableBorderTop

- packages/ui-core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/ui-core/src/components/Collapse/Collapse.less
- packages/ui-core/src/components/Collapse/Collapse.tsx
---
```
"version": "4.14.1"
"version": "4.14.1"
```
* **collapse:** new prop openedClassName ([c7fa687](https://github.com/MegafonWebLab/megafon-ui/commit/c7fa6876221ab02fff892e9e11772343d78c7444))
> fix(collapse): new prop openedClassName

- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Search/Search.test.tsx
- packages/ui-core/src/components/Search/Search.tsx
- packages/ui-core/src/components/Search/__snapshots__/Search.test.tsx.snap
- packages/ui-core/src/components/Search/doc/Search.example.mdx
---
```
"version": "4.14.1"
"version": "4.14.1"
```
* **search:** new props showLoader and type ([1bd81df](https://github.com/MegafonWebLab/megafon-ui/commit/1bd81dfd1beae622ee33a0e6dac3cb95b7454c41))
> fix(search): new props showLoader and type

- packages/ui-core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/ui-core/src/components/Collapse/Collapse.less
- packages/ui-core/src/components/Collapse/Collapse.tsx
- packages/ui-core/src/components/Search/Search.less
- packages/ui-core/src/components/Search/Search.test.tsx
- packages/ui-core/src/components/Search/Search.tsx
- packages/ui-core/src/components/Search/__snapshots__/Search.test.tsx.snap
- packages/ui-core/src/components/Search/doc/Search.example.mdx
- packages/ui-shared/src/components/ButtonBanner/ButtonBanner.less
- packages/ui-shared/src/components/Card/Card.less
- packages/ui-shared/src/components/StoreBanner/StoreBanner.less
- packages/ui-shared/src/components/StoreBanner/StoreBanner.tsx
- packages/ui-shared/src/components/StoreBanner/doc/StoreBanner.example.mdx
---
```
"version": "4.14.1"
```
* **collapse:** new prop openedClassName ([c7fa687](https://github.com/MegafonWebLab/megafon-ui/commit/c7fa6876221ab02fff892e9e11772343d78c7444))
* **search:** new props showLoader and type ([1bd81df](https://github.com/MegafonWebLab/megafon-ui/commit/1bd81dfd1beae622ee33a0e6dac3cb95b7454c41))
* **storebanner:** add new theme ([908aa58](https://github.com/MegafonWebLab/megafon-ui/commit/908aa588067c8e450ef17b10a9c9025bfae9d3c1))
> 20.03.2023 release

- packages/ui-core/src/components/Select/Select.less
---
```
```
* **select:** fix pseudo element position, fix z-index of drop-down list ([8d74450](https://github.com/MegafonWebLab/megafon-ui/commit/8d744504b0829323a94727a49823ec4d6a6e0d0d))
> feat(select): fix pseudo element position, fix z-index of drop-down list

- packages/ui-core/src/components/Select/Select.less
---
```
"version": "4.14.3"
```
* **select:** reduce opened z index ([eb95b6b](https://github.com/MegafonWebLab/megafon-ui/commit/eb95b6b5ff4d18c0e782a571428fdb4680e11474))
> fix(select): reduce opened z index

- packages/ui-shared/package.json
- packages/ui-shared/src/components/AudioPlayer/AudioProgress.tsx
- packages/ui-shared/src/components/AudioPlayer/hooks/useTrackDuration.ts
- packages/ui-shared/src/components/AudioPlayer/test/AudioProgress.test.tsx
- packages/ui-shared/src/components/AudioPlayer/test/useTrackDuration.test.ts
- yarn.lock
---
```
```
* **audioplayer:** fix loading of audio metadata ([d3a496d](https://github.com/MegafonWebLab/megafon-ui/commit/d3a496d6b3be86627f41d001376f6e20df0275b5))
> fix(audioplayer): fix loading of audio metadata

- packages/ui-shared/src/components/AudioPlayer/AudioPlayer.tsx
- packages/ui-shared/src/components/AudioPlayer/AudioProgress.tsx
- packages/ui-shared/src/components/AudioPlayer/AudioRange.tsx
- packages/ui-shared/src/components/AudioPlayer/AudioVolume.tsx
- packages/ui-shared/src/components/AudioPlayer/test/AudioPlayer.test.tsx
- packages/ui-shared/src/components/AudioPlayer/test/AudioProgress.test.tsx
- packages/ui-shared/src/components/AudioPlayer/test/AudioRange.test.tsx
- packages/ui-shared/src/components/AudioPlayer/test/AudioVolume.test.tsx
- packages/ui-shared/src/components/AudioPlayer/test/__snapshots__/AudioPlayer.test.tsx.snap
- packages/ui-shared/src/components/AudioPlayer/test/__snapshots__/AudioProgress.test.tsx.snap
- packages/ui-shared/src/components/AudioPlayer/test/__snapshots__/AudioRange.test.tsx.snap
- packages/ui-shared/src/components/AudioPlayer/test/__snapshots__/AudioVolume.test.tsx.snap
> test(audioplayer): rewrite tests

- packages/ui-core/src/components/Carousel/Carousel.less
- packages/ui-core/src/components/Carousel/Carousel.test.tsx
- packages/ui-core/src/components/Carousel/Carousel.tsx
- packages/ui-core/src/components/Carousel/doc/Carousel.docz.tsx
- packages/ui-core/src/components/Carousel/doc/Carousel.example.mdx
- packages/ui-core/src/components/Carousel/useGradient.ts
---
```
"version": "4.15.2"
"version": "4.16.0"
"version": "4.16.1"
```
* **carousel:** fix gradientColor type and gradient height ([2d7eea0](https://github.com/MegafonWebLab/megafon-ui/commit/2d7eea0f215433912542a5a6eb99f48c7331a6d2))
> fix(carousel): fix gradientColor type and gradient height

- packages/ui-shared/src/components/Instructions/Instructions.less
- packages/ui-shared/src/components/Instructions/Instructions.tsx
- packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
- packages/ui-shared/src/components/Instructions/doc/Instructions.example.mdx
---
```
"version": "4.17.0"
"version": "4.18.0"
```
* **instructions:** add prop pictureVerticalAlign ([e380224](https://github.com/MegafonWebLab/megafon-ui/commit/e38022435ce3a5eaf2864bf6ed5a0028e81c9ec1))
> feat(instructions): add prop pictureVerticalAlign

- packages/ui-core/src/components/Tabs/Tabs.less
- packages/ui-core/src/components/Tabs/Tabs.tsx
- packages/ui-shared/src/components/Instructions/Instructions.less
---
```
"version": "4.15.2"
"version": "4.15.3"
"version": "4.17.0"
"version": "4.17.1"
```
* **tabs:** fixed tabs scroll on mobile resolution, set hover for desktop ([f18da75](https://github.com/MegafonWebLab/megafon-ui/commit/f18da7552911bca92ea1b1229c70ecad810d30ae))
* **instructions:** fixed screen scroll for iphone devices ([fae9838](https://github.com/MegafonWebLab/megafon-ui/commit/fae98383271ed7a291665cbb7f9011d17ec0bc93))
> 14621 fix tabs instructions

- packages/ui-core/src/components/Tabs/Tabs.less
- packages/ui-core/src/components/Tabs/Tabs.tsx
---
```
"version": "4.15.3"
"version": "4.15.4"
"version": "4.18.0"
"version": "4.18.1"
```
* **tabs:** fixed gradient on swiper edges ([650e9be](https://github.com/MegafonWebLab/megafon-ui/commit/650e9beea8318ccf7bf564b4473a9d3487457694))
> fix(tabs): fixed gradient on swiper edges
