MegafonWebLab/megafon-ui

packages/ui-core/src/components/Select/Select.less
fixes wrong font weight in select when parent element has its own font weight
=> fix(select): default font weight added

packages/ui-core/src/components/Tabs/Tabs.less
border is stretched to full width if tabs have left align
=> style(tabs): edit tabs border

packages/ui-core/src/components/Carousel/Carousel.tsx, packages/ui-core/src/components/Carousel/__snapshots__/Carousel.test.tsx.snap
По дефолту в параметр noSwipingSelector добавлен класс контейнера пагинации, чтобы отключить свайп при клике на точки пагинации и устранить баг с неверным переключением слайдов.
Также убрано дефолтное значение параметра threshold.
=> fix(carousel): turn off swiping on pagination

packages/ui-core/src/components/Carousel/Carousel.tsx
---
```
"version": "3.0.4"
```
* **carousel:** add resize listener to nav display ([12abd93](https://github.com/MegafonWebLab/megafon-ui/commit/12abd93d226676d2c4f78968c9d5de032783ec8d))
=> fix(carousel): add resize listener to nav display

packages/ui-core/src/components/Tile/Tile.test.tsx, packages/ui-core/src/components/Tile/Tile.tsx, packages/ui-core/src/components/Tile/__snapshots__/Tile.test.tsx.snap, packages/ui-core/src/components/Tile/doc/Tile.example.mdx
---
```
```
* **tile:** delete unnecessary symbol ([1f0ed90](https://github.com/MegafonWebLab/megafon-ui/commit/1f0ed9009ef2cb9e5562f257640a623eceae225e))
* **tile:** add target props for link ([e49d040](https://github.com/MegafonWebLab/megafon-ui/commit/e49d0402725e88b9fd7d80fd418acd81bea321ba))
=> feat(tile): add target props for link

packages/ui-core/src/components/Accordion/Accordion.less
---
```
"version": "3.1.2"
```
* **accordion:** remove outline for safari ([787b572](https://github.com/MegafonWebLab/megafon-ui/commit/787b5725ef962637401a0a3a1a8ae7ba0cece031))
=> fix(accordion): remove outline for safari

packages/ui-icons/src/doc/Icons.less
---
```
"version": "1.1.0"
"version": "1.1.1"
```
=> docs(icons): added fixed width of 32px to fix firefox display

packages/ui-core/src/components/Search/Search.tsx
- `Search`: scroll highlighted item into users view. useful with keyboard control.
---
```
```
* **search:** scroll highlighted item into users view ([5105863](https://github.com/MegafonWebLab/megafon-ui/commit/51058637a78598773e945b1f21eecbc319d7df78))
=> fix(search): scroll highlighted item into users view

packages/ui-core/src/components/Select/Select.tsx
- `Select`: smooth scroll highlighted item into users view
---
```
```
* **select:** scroll highlighted item into users view ([50860e8](https://github.com/MegafonWebLab/megafon-ui/commit/50860e82a557cd6dd2e89448740a13b6e25c8261))
=> fix(select): smooth scroll highlighted item into users view

packages/ui-icons/src/Service-logos/24/Yandex-disk.svg, packages/ui-icons/src/Service-logos/24/Yandex-navigator.svg
BREAKING CHANGE: renamed import paths for yandex-disc and yandex-naviator icons (fixed icon names)
---
```
"version": "1.1.1"
"version": "2.0.0"
```
* **ui-icons:** fixed service icon names ([02035e8](https://github.com/MegafonWebLab/megafon-ui/commit/02035e8c053d9780d11313ffd56ca9a5d0e9bfd0))
* **ui-icons:** renamed import paths for yandex-disc and yandex-naviator icons (fixed icon names)
=> fix(ui-icons): fixed service icon names

packages/ui-core/src/components/Notification/Notification.test.tsx, packages/ui-core/src/components/Notification/Notification.tsx, packages/ui-core/src/components/Notification/__snapshots__/Notification.test.tsx.snap
Fix text width and align on mobile resolution in Notification component.
---
```
"version": "3.7.0"
"version": "3.3.3"
```
* **notification:** add props classes to notification component ([608a424](https://github.com/MegafonWebLab/megafon-ui/commit/608a4246eb99af354fb7cf8ab98c2ed513d87b66))
=> feat(notification): add props classes to notification component

packages/ui-shared/src/components/Breadcrumbs/Breadcrumbs.tsx, packages/ui-shared/src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
new default value for prop 'color' is 'default' instead of 'black'
BREAKING CHANGE: color is now depends on current theme. by default it matches content text color.
for keep black color on light background use 'black' value for prop 'color'.
---
```
"version": "4.0.0"
```
* **breadcrumbs:** change default color prop value from black to default ([9c2c0fc](https://github.com/MegafonWebLab/megafon-ui/commit/9c2c0fca7d559a67d3d167b2a8a3c30b420ab7da))
* **breadcrumbs:** color is now depends on current theme. by default it matches content text color.
for keep black color on light background use 'black' value for prop 'color'.
=> fix(breadcrumbs): change default color prop value from black to default

packages/ui-core/src/components/Select/Select.tsx, packages/ui-core/src/components/Select/doc/Select.docz.tsx, packages/ui-core/src/components/Select/doc/Select.example.mdx
---
```
"version": "3.8.1"
```
* **select:** fix selected item color when value is zero ([9847095](https://github.com/MegafonWebLab/megafon-ui/commit/98470955ef813504d4bfa4cd4d3aba77b5458446))
=> fix(select): fix selected item color when value is zero

packages/ui-core/src/components/Switcher/Switcher.test.tsx, packages/ui-core/src/components/Switcher/Switcher.tsx, packages/ui-core/src/components/Switcher/__snapshots__/Switcher.test.tsx.snap
---
```
"version": "3.9.0"
```
* **switcher:** add data-attribute for inner element ([793a022](https://github.com/MegafonWebLab/megafon-ui/commit/793a0224ab957b938e67dd1b4d16c2389a9fb6f8))
=> feat(switcher): add data-attribute for inner element

packages/ui-core/src/components/Button/Button.less, packages/ui-core/src/components/Button/Button.test.tsx, packages/ui-core/src/components/Button/Button.tsx, packages/ui-core/src/components/Button/doc/Button.example.mdx, packages/ui-core/src/components/Notification/Notification.less, packages/ui-core/src/components/Notification/Notification.test.tsx, packages/ui-core/src/components/Notification/Notification.tsx, packages/ui-core/src/components/Notification/__snapshots__/Notification.test.tsx.snap, packages/ui-core/src/components/Notification/doc/Notification.docz.tsx, packages/ui-core/src/components/Notification/doc/Notification.example.mdx, src/gatsby-theme-docz/components/Layout/Layout.less, src/gatsby-theme-docz/index.less
---
```
"version": "3.10.1"
"version": "3.11.0"
"version": "3.4.1"
"version": "3.4.2"
```
* **button:** fix font styles for extra small size ([f475b05](https://github.com/MegafonWebLab/megafon-ui/commit/f475b05ab9d62aa56645fb90ccdef88996e72a70))
* **button:** add prop ellipsis ([1978277](https://github.com/MegafonWebLab/megafon-ui/commit/1978277a918cb680e32259042c1a7e3c58056b1b))
* **notification:** add ability to display button and collapse ([a5fe2f0](https://github.com/MegafonWebLab/megafon-ui/commit/a5fe2f0730b71469c2fb06a148b0e4574adb2d7b))
=> feat(notification): add ability to display button and collapse 

packages/ui-core/src/components/Notification/Notification.tsx
---
```
"version": "3.10.1"
"version": "3.11.0"
"version": "3.4.1"
"version": "3.4.2"
```
* **button:** fix font styles for extra small size ([f475b05](https://github.com/MegafonWebLab/megafon-ui/commit/f475b05ab9d62aa56645fb90ccdef88996e72a70))
* **button:** add prop ellipsis ([1978277](https://github.com/MegafonWebLab/megafon-ui/commit/1978277a918cb680e32259042c1a7e3c58056b1b))
* **notification:** add ability to display button and collapse ([a5fe2f0](https://github.com/MegafonWebLab/megafon-ui/commit/a5fe2f0730b71469c2fb06a148b0e4574adb2d7b))
=> refactor(notification): remove redundant state

packages/ui-core/src/components/Tabs/Tab.tsx, packages/ui-core/src/components/Tabs/Tabs.test.tsx, packages/ui-core/src/components/Tabs/Tabs.tsx, packages/ui-core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
---
```
"version": "3.11.0"
"version": "3.12.0"
"version": "3.4.2"
"version": "3.4.3"
```
* **tab:** add data-attribute for inner element ([43e58e1](https://github.com/MegafonWebLab/megafon-ui/commit/43e58e12b8da661020f4b48f55245492c21ad376))
=> feat(tab): add data-attribute for inner element

packages/ui-shared/src/components/TextWithIcon/TextWithIcon.less, packages/ui-shared/src/components/TextWithIcon/TextWithIconItem.less
---
```
"version": "4.0.0-beta.1"
"version": "4.0.0-beta.2"
```
* **text-with-icon:** delete centering in mobile resolution ([1557a8c](https://github.com/MegafonWebLab/megafon-ui/commit/1557a8cf334ad52143578daccd41c08c06d6254d))
* **text-with-icon:** centering in mobile resolution was removed according guides
=> feat(text-with-icon): delete centering in mobile resolution

packages/ui-core/package.json
---
```
"version": "3.12.0"
"version": "3.12.1"
"version": "3.4.3"
"version": "3.4.4"
```
=> chore: ui-core: update peerDependency of ui-icons to ^1.0.0

packages/ui-core/src/components/TextField/TextField.less
---
```
"version": "4.0.0-beta.19"
"version": "4.0.0-beta.20"
"version": "4.0.0-beta.20"
"version": "4.0.0-beta.21"
```
* **textfield:** returned correct color to notice text ([d6ef976](https://github.com/MegafonWebLab/megafon-ui/commit/d6ef976f755e1fb55d7fd2e462095459d96b74c9))
=> fix(textfield): returned correct color to notice text

packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx, packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx, packages/ui-shared/src/components/VideoBanner/__snapshots__/VideoBanner.test.tsx.snap, packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.props.mdx
---
```
"version": "3.4.6"
```
* **videobanner:** add buttonTarget and linkTarget props ([96dcfbc](https://github.com/MegafonWebLab/megafon-ui/commit/96dcfbc4ecffeb9fca9e9e15d2a5434e1b978481))
=> feat(videobanner): add buttonTarget and linkTarget props

packages/ui-core/src/colors/colorsData.tsx, packages/ui-core/src/components/Button/Button.less, packages/ui-core/src/styles/colors.css, packages/ui-core/src/styles/colorsDark.css, packages/ui-helpers/src/applyTheme.ts
---
```
"version": "4.0.2"
"version": "4.1.0"
"version": "2.1.2"
"version": "2.2.0"
"version": "2.0.0"
"version": "2.0.1"
"version": "4.0.2"
"version": "4.0.3"
```
* **button:** changed white themed primary typed button hover color ([a6e6c98](https://github.com/MegafonWebLab/megafon-ui/commit/a6e6c98eb9716f3ba33d651f71dcb9e4298ad0a0))
* **color:** added grey button hover color ([b291e83](https://github.com/MegafonWebLab/megafon-ui/commit/b291e831bb9e35144cdf83895b43df4856a364cf))
* **color:** added grey button hover color ([b291e83](https://github.com/MegafonWebLab/megafon-ui/commit/b291e831bb9e35144cdf83895b43df4856a364cf))
**Note:** …
=> Change white button hover

packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx, packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.docz.tsx, packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.example.mdx
List of allowed html-tag: "&lt;br&gt;, &nbsp, &lt;b&gt;, &lt;font color&gt;, &lt;a href&gt;"
---
```
"version": "4.0.3"
"version": "4.1.0"
```
* **videobanner:** allow using html tag: br, &nbsp, b, font color, a href in title and description ([31cf562](https://github.com/MegafonWebLab/megafon-ui/commit/31cf562b34f9d6eb30a43fccd1123fdc67393935))
=> feat(videobanner): allow using html tag in title and description of videobanner

packages/ui-core/src/components/TextField/TextField.less
set margin to 0 for input in TextField which fixes component height in Safari
---
```
"version": "4.1.1"
```
* **textfield:** fix input height in Safari ([b60e1ac](https://github.com/MegafonWebLab/megafon-ui/commit/b60e1acd76dc80b4609b55dc8256eb94e8e8ec0c))
=> fix(textfield): fix input height in Safari

packages/ui-shared/src/components/Card/Card.test.tsx, packages/ui-shared/src/components/Card/Card.tsx, packages/ui-shared/src/components/Card/__snapshots__/Card.test.tsx.snap, packages/ui-shared/src/components/Card/doc/Card.docz.tsx, packages/ui-shared/src/components/Card/doc/Card.example.mdx, packages/ui-shared/src/components/Card/doc/Card.props.mdx
- add for `button` prop `onClick` property
- make `button` prop `href` property optional
---
```
"version": "4.2.0"
```
* **card:** add tests for button onClick; fix propTypes; ([148ca04](https://github.com/MegafonWebLab/megafon-ui/commit/148ca04afb9194eff52421ca228dd4de5e094323))
* **card:** add button onClick property ([766c66f](https://github.com/MegafonWebLab/megafon-ui/commit/766c66f609ee5a20b86322acd5a40dfc14cee223))
=> feat(card): add button onClick property

packages/ui-core/src/components/TextField/TextField.test.tsx, packages/ui-core/src/components/TextField/TextField.tsx, packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/ui-core/src/components/TextField/doc/TextField.example.mdx
---
```
"version": "4.2.0"
```
* **textfield:** add minTextareaHeight and hideResizeButton props for textarea ([088d219](https://github.com/MegafonWebLab/megafon-ui/commit/088d21971b69233522bb5cf7d642cffbc2571ca4))
=> Add minTextareaHeight and hideResizeButton props for textarea

packages/ui-shared/src/components/VideoBlock/VideoBlock.less, packages/ui-shared/src/components/VideoBlock/VideoBlock.test.tsx, packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx, packages/ui-shared/src/components/VideoBlock/__snapshots__/VideoBlock.test.tsx.snap, packages/ui-shared/src/components/VideoBlock/doc/VideoBlock.example.mdx
add prop contentPositionRight to place content after video
---
```
```
* **videoblock:** add prop contentPositionRight ([6f1e603](https://github.com/MegafonWebLab/megafon-ui/commit/6f1e603c1cd3489a18a9ccf5da5e1e0785c4f0cf))
=> feat(videoblock): add prop contentPositionRight

packages/ui-core/src/components/TextField/TextField.less, packages/ui-core/src/components/TextField/TextField.tsx, packages/ui-core/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/ui-core/src/components/TextField/doc/TextField.example.mdx
---
```
"version": "4.6.1"
```
* **textfield:** fix right padding with hideIcon prop ([c2aeffd](https://github.com/MegafonWebLab/megafon-ui/commit/c2aeffd1e4c94c97aac23128b9f1ccff4ead9a81))
=> fix(textfield): fix right padding with hideIcon prop

packages/ui-shared/src/components/AccordionBox/AccordionBox.less, packages/ui-shared/src/components/AccordionBox/doc/AccordionBox.example.mdx
---
```
```
* **accordionbox:** add missing margin for group of components ([e20da93](https://github.com/MegafonWebLab/megafon-ui/commit/e20da9336f664b526671e5950d319e8ef4dbd946))
=> fix(accordionbox): add missing margin for group of components

packages/ui-shared/src/components/VideoBlock/VideoBlock.test.tsx, packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx, packages/ui-shared/src/components/VideoBlock/__snapshots__/VideoBlock.test.tsx.snap, packages/ui-shared/src/components/VideoBlock/doc/VideoBlock.example.mdx
---
```
```
* **videoblock:** added for title and description render html tags ([d0d2255](https://github.com/MegafonWebLab/megafon-ui/commit/d0d2255abb80e73058151967721a447c8ebc4028))
* **videoblock:** fixed and ddded tag b for description ([6e7de85](https://github.com/MegafonWebLab/megafon-ui/commit/6e7de853b8ff920f4b0de2ecfd3cdb8538bc727a))
* **videoblock:** return types and change config for description ([75f18e1](https://github.com/MegafonWebLab/megafon-ui/commit/75f18e10e6cb22779cceaf90f8a6e0e258a92612))
=> feat(videoblock): added for title and description render html tags

packages/ui-core/src/components/Tabs/Tabs.less
---
```
"version": "4.8.2"
```
* **tabs:** remove tab underline on hover ([1c6cfbd](https://github.com/MegafonWebLab/megafon-ui/commit/1c6cfbde1c66c71c99c42ae4a586f048688f3afb))
=> fix(tabs): remove tab underline on hover

packages/ui-shared/src/components/TextWithIcon/TextWithIconItem.test.tsx, packages/ui-shared/src/components/TextWithIcon/TextWithIconItem.tsx, packages/ui-shared/src/components/TextWithIcon/__snapshots__/TextWithIconItem.test.tsx.snap, packages/ui-shared/src/components/TextWithIcon/doc/TextWithIcon.example.mdx
---
```
```
* **textwithicon:** fix playground ([44c4b6a](https://github.com/MegafonWebLab/megafon-ui/commit/44c4b6ad323a88f48d3b79191e3be4c44fa2ac14))
* **textwithiconitem:** add example and fix text ([3db8692](https://github.com/MegafonWebLab/megafon-ui/commit/3db869242615caacf1101e4fcff1877ee43c9c95))
* **textwithiconitem:** add render html and classes ([74e21bc](https://github.com/MegafonWebLab/megafon-ui/commit/74e21bcb78e3f4764ceb58d8fa102b6b000c5ae2))
=> feat(textwithiconitem): add render html and classes

packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx, packages/ui-shared/src/components/BenefitsPictures/__snapshots__/BenefitPictures.test.tsx.snap, packages/ui-shared/src/components/BenefitsPictures/doc/BenefitsPictures.docz.tsx, packages/ui-shared/src/components/BenefitsPictures/types.ts, packages/ui-shared/src/components/Card/Card.test.tsx, packages/ui-shared/src/components/Card/Card.tsx, packages/ui-shared/src/components/Card/__snapshots__/Card.test.tsx.snap, packages/ui-shared/src/components/Instructions/Instructions.test.tsx, packages/ui-shared/src/components/Instructions/Instructions.tsx, packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap, packages/ui-shared/src/components/PictureWithDescription/PictureWithDescription.test.tsx, packages/ui-shared/src/components/PictureWithDescription/PictureWithDescription.tsx, packages/ui-shared/src/components/PictureWithDescription/__snapshots__/PictureWithDescription.test.tsx.snap, packages/ui-shared/src/components/TextBox/TextBoxPicture.test.tsx, packages/ui-shared/src/components/TextBox/TextBoxPicture.tsx, packages/ui-shared/src/components/TextBox/__snapshots__/TextBoxPicture.test.tsx.snap, packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx, packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx, packages/ui-shared/src/components/VideoBanner/__snapshots__/VideoBanner.test.tsx.snap
---
```
```
* **benefitpictures:** add alt prop for images ([3fd19e7](https://github.com/MegafonWebLab/megafon-ui/commit/3fd19e718068db8d418adccbb1812e4e8dd6e090))
* **card:** add alt prop for image ([a56a159](https://github.com/MegafonWebLab/megafon-ui/commit/a56a1595b1114e63aa80d9f8976bfb8d54b871db))
* **instructions:** add alt prop for images ([94d4750](https://github.com/MegafonWebLab/megafon-ui/commit/94d4750a51a4d3e848c319ed98a31b3fd241e733))
* **picturewithdescription:** add alt prop for image ([0ed9e19](https://github.com/MegafonWebLab/megafon-ui/commit/0ed9e195b00c41a2a736de741af82b3808eb1677))
* **textboxpicture:** add alt prop for image …
=> add alt prop for images

packages/ui-icons/src/Service-logos/24/Apple-map.svg
---
```
"version": "4.14.3"
"version": "2.8.0"
"version": "2.8.1"
```
* **icons:** replace Apple-map.svg icon for fix missing <mask /> issue after SVGO ([90a4a87](https://github.com/MegafonWebLab/megafon-ui/commit/90a4a87d27cdd565d50295956165c26b4739b40f))
=> fix(icons): replace Apple-map.svg icon

packages/ui-core/src/components/Button/Button.less, packages/ui-core/src/components/Button/Button.tsx, packages/ui-core/src/components/Button/doc/Button.example.mdx
---
```
"version": "4.15.2"
```
* **color:** new danger color for text type button ([7f53fd8](https://github.com/MegafonWebLab/megafon-ui/commit/7f53fd8d369f664e678c8cb2a437ef4fa5c801fc))
=> fix(color): new danger color for text type button

packages/ui-core/src/components/Badges/components/PriceBadge/PriceBadge.less, packages/ui-core/src/components/Badges/components/PriceBadge/PriceBadge.test.tsx, packages/ui-core/src/components/Badges/components/PriceBadge/PriceBadge.tsx, packages/ui-core/src/components/Badges/components/PriceBadge/__snapshots__/PriceBadge.test.tsx.snap, packages/ui-core/src/components/Badges/components/PriceBadge/doc/PriceBadge.example.mdx
---
```
"version": "4.15.2"
```
* **pricebadge:** new props size and subtitle ([5f40360](https://github.com/MegafonWebLab/megafon-ui/commit/5f40360509e703a8fab2f4936aa109a9b63bafcd))
=> fix(pricebadge): new props size and subtitle
